<?php
/**
 * AdvancedSecurityActiveCommitters
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model;

use \ArrayAccess;
use \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\ObjectSerializer;

/**
 * AdvancedSecurityActiveCommitters Class Doc Comment
 *
 * @category Class
 * @package  System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AdvancedSecurityActiveCommitters implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'advanced-security-active-committers';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'total_advanced_security_committers' => 'int',
        'total_count' => 'int',
        'maximum_advanced_security_committers' => 'int',
        'purchased_advanced_security_committers' => 'int',
        'repositories' => '\System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\AdvancedSecurityActiveCommittersRepository[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'total_advanced_security_committers' => null,
        'total_count' => null,
        'maximum_advanced_security_committers' => null,
        'purchased_advanced_security_committers' => null,
        'repositories' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'total_advanced_security_committers' => false,
        'total_count' => false,
        'maximum_advanced_security_committers' => false,
        'purchased_advanced_security_committers' => false,
        'repositories' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'total_advanced_security_committers' => 'total_advanced_security_committers',
        'total_count' => 'total_count',
        'maximum_advanced_security_committers' => 'maximum_advanced_security_committers',
        'purchased_advanced_security_committers' => 'purchased_advanced_security_committers',
        'repositories' => 'repositories'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'total_advanced_security_committers' => 'setTotalAdvancedSecurityCommitters',
        'total_count' => 'setTotalCount',
        'maximum_advanced_security_committers' => 'setMaximumAdvancedSecurityCommitters',
        'purchased_advanced_security_committers' => 'setPurchasedAdvancedSecurityCommitters',
        'repositories' => 'setRepositories'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'total_advanced_security_committers' => 'getTotalAdvancedSecurityCommitters',
        'total_count' => 'getTotalCount',
        'maximum_advanced_security_committers' => 'getMaximumAdvancedSecurityCommitters',
        'purchased_advanced_security_committers' => 'getPurchasedAdvancedSecurityCommitters',
        'repositories' => 'getRepositories'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('total_advanced_security_committers', $data ?? [], null);
        $this->setIfExists('total_count', $data ?? [], null);
        $this->setIfExists('maximum_advanced_security_committers', $data ?? [], null);
        $this->setIfExists('purchased_advanced_security_committers', $data ?? [], null);
        $this->setIfExists('repositories', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['repositories'] === null) {
            $invalidProperties[] = "'repositories' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets total_advanced_security_committers
     *
     * @return int|null
     */
    public function getTotalAdvancedSecurityCommitters()
    {
        return $this->container['total_advanced_security_committers'];
    }

    /**
     * Sets total_advanced_security_committers
     *
     * @param int|null $total_advanced_security_committers total_advanced_security_committers
     *
     * @return self
     */
    public function setTotalAdvancedSecurityCommitters($total_advanced_security_committers)
    {
        if (is_null($total_advanced_security_committers)) {
            throw new \InvalidArgumentException('non-nullable total_advanced_security_committers cannot be null');
        }
        $this->container['total_advanced_security_committers'] = $total_advanced_security_committers;

        return $this;
    }

    /**
     * Gets total_count
     *
     * @return int|null
     */
    public function getTotalCount()
    {
        return $this->container['total_count'];
    }

    /**
     * Sets total_count
     *
     * @param int|null $total_count total_count
     *
     * @return self
     */
    public function setTotalCount($total_count)
    {
        if (is_null($total_count)) {
            throw new \InvalidArgumentException('non-nullable total_count cannot be null');
        }
        $this->container['total_count'] = $total_count;

        return $this;
    }

    /**
     * Gets maximum_advanced_security_committers
     *
     * @return int|null
     */
    public function getMaximumAdvancedSecurityCommitters()
    {
        return $this->container['maximum_advanced_security_committers'];
    }

    /**
     * Sets maximum_advanced_security_committers
     *
     * @param int|null $maximum_advanced_security_committers The total number of GitHub Advanced Security licences required if all repositories were to enable GitHub Advanced Security
     *
     * @return self
     */
    public function setMaximumAdvancedSecurityCommitters($maximum_advanced_security_committers)
    {
        if (is_null($maximum_advanced_security_committers)) {
            throw new \InvalidArgumentException('non-nullable maximum_advanced_security_committers cannot be null');
        }
        $this->container['maximum_advanced_security_committers'] = $maximum_advanced_security_committers;

        return $this;
    }

    /**
     * Gets purchased_advanced_security_committers
     *
     * @return int|null
     */
    public function getPurchasedAdvancedSecurityCommitters()
    {
        return $this->container['purchased_advanced_security_committers'];
    }

    /**
     * Sets purchased_advanced_security_committers
     *
     * @param int|null $purchased_advanced_security_committers The total number of GitHub Advanced Security licences purchased
     *
     * @return self
     */
    public function setPurchasedAdvancedSecurityCommitters($purchased_advanced_security_committers)
    {
        if (is_null($purchased_advanced_security_committers)) {
            throw new \InvalidArgumentException('non-nullable purchased_advanced_security_committers cannot be null');
        }
        $this->container['purchased_advanced_security_committers'] = $purchased_advanced_security_committers;

        return $this;
    }

    /**
     * Gets repositories
     *
     * @return \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\AdvancedSecurityActiveCommittersRepository[]
     */
    public function getRepositories()
    {
        return $this->container['repositories'];
    }

    /**
     * Sets repositories
     *
     * @param \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\AdvancedSecurityActiveCommittersRepository[] $repositories repositories
     *
     * @return self
     */
    public function setRepositories($repositories)
    {
        if (is_null($repositories)) {
            throw new \InvalidArgumentException('non-nullable repositories cannot be null');
        }
        $this->container['repositories'] = $repositories;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


