<?php
/**
 * CopilotUsageMetricsBreakdownInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model;

use \ArrayAccess;
use \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\ObjectSerializer;

/**
 * CopilotUsageMetricsBreakdownInner Class Doc Comment
 *
 * @category Class
 * @description Breakdown of Copilot usage by editor for this language
 * @package  System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CopilotUsageMetricsBreakdownInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'copilot_usage_metrics_breakdown_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'language' => 'string',
        'editor' => 'string',
        'suggestions_count' => 'int',
        'acceptances_count' => 'int',
        'lines_suggested' => 'int',
        'lines_accepted' => 'int',
        'active_users' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'language' => null,
        'editor' => null,
        'suggestions_count' => null,
        'acceptances_count' => null,
        'lines_suggested' => null,
        'lines_accepted' => null,
        'active_users' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'language' => false,
        'editor' => false,
        'suggestions_count' => false,
        'acceptances_count' => false,
        'lines_suggested' => false,
        'lines_accepted' => false,
        'active_users' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'language' => 'language',
        'editor' => 'editor',
        'suggestions_count' => 'suggestions_count',
        'acceptances_count' => 'acceptances_count',
        'lines_suggested' => 'lines_suggested',
        'lines_accepted' => 'lines_accepted',
        'active_users' => 'active_users'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'language' => 'setLanguage',
        'editor' => 'setEditor',
        'suggestions_count' => 'setSuggestionsCount',
        'acceptances_count' => 'setAcceptancesCount',
        'lines_suggested' => 'setLinesSuggested',
        'lines_accepted' => 'setLinesAccepted',
        'active_users' => 'setActiveUsers'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'language' => 'getLanguage',
        'editor' => 'getEditor',
        'suggestions_count' => 'getSuggestionsCount',
        'acceptances_count' => 'getAcceptancesCount',
        'lines_suggested' => 'getLinesSuggested',
        'lines_accepted' => 'getLinesAccepted',
        'active_users' => 'getActiveUsers'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('editor', $data ?? [], null);
        $this->setIfExists('suggestions_count', $data ?? [], null);
        $this->setIfExists('acceptances_count', $data ?? [], null);
        $this->setIfExists('lines_suggested', $data ?? [], null);
        $this->setIfExists('lines_accepted', $data ?? [], null);
        $this->setIfExists('active_users', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets language
     *
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string|null $language The language in which Copilot suggestions were shown to users in the specified editor.
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets editor
     *
     * @return string|null
     */
    public function getEditor()
    {
        return $this->container['editor'];
    }

    /**
     * Sets editor
     *
     * @param string|null $editor The editor in which Copilot suggestions were shown to users for the specified language.
     *
     * @return self
     */
    public function setEditor($editor)
    {
        if (is_null($editor)) {
            throw new \InvalidArgumentException('non-nullable editor cannot be null');
        }
        $this->container['editor'] = $editor;

        return $this;
    }

    /**
     * Gets suggestions_count
     *
     * @return int|null
     */
    public function getSuggestionsCount()
    {
        return $this->container['suggestions_count'];
    }

    /**
     * Sets suggestions_count
     *
     * @param int|null $suggestions_count The number of Copilot suggestions shown to users in the editor specified during the day specified.
     *
     * @return self
     */
    public function setSuggestionsCount($suggestions_count)
    {
        if (is_null($suggestions_count)) {
            throw new \InvalidArgumentException('non-nullable suggestions_count cannot be null');
        }
        $this->container['suggestions_count'] = $suggestions_count;

        return $this;
    }

    /**
     * Gets acceptances_count
     *
     * @return int|null
     */
    public function getAcceptancesCount()
    {
        return $this->container['acceptances_count'];
    }

    /**
     * Sets acceptances_count
     *
     * @param int|null $acceptances_count The number of Copilot suggestions accepted by users in the editor specified during the day specified.
     *
     * @return self
     */
    public function setAcceptancesCount($acceptances_count)
    {
        if (is_null($acceptances_count)) {
            throw new \InvalidArgumentException('non-nullable acceptances_count cannot be null');
        }
        $this->container['acceptances_count'] = $acceptances_count;

        return $this;
    }

    /**
     * Gets lines_suggested
     *
     * @return int|null
     */
    public function getLinesSuggested()
    {
        return $this->container['lines_suggested'];
    }

    /**
     * Sets lines_suggested
     *
     * @param int|null $lines_suggested The number of lines of code suggested by Copilot in the editor specified during the day specified.
     *
     * @return self
     */
    public function setLinesSuggested($lines_suggested)
    {
        if (is_null($lines_suggested)) {
            throw new \InvalidArgumentException('non-nullable lines_suggested cannot be null');
        }
        $this->container['lines_suggested'] = $lines_suggested;

        return $this;
    }

    /**
     * Gets lines_accepted
     *
     * @return int|null
     */
    public function getLinesAccepted()
    {
        return $this->container['lines_accepted'];
    }

    /**
     * Sets lines_accepted
     *
     * @param int|null $lines_accepted The number of lines of code accepted by users in the editor specified during the day specified.
     *
     * @return self
     */
    public function setLinesAccepted($lines_accepted)
    {
        if (is_null($lines_accepted)) {
            throw new \InvalidArgumentException('non-nullable lines_accepted cannot be null');
        }
        $this->container['lines_accepted'] = $lines_accepted;

        return $this;
    }

    /**
     * Gets active_users
     *
     * @return int|null
     */
    public function getActiveUsers()
    {
        return $this->container['active_users'];
    }

    /**
     * Sets active_users
     *
     * @param int|null $active_users The number of users who were shown Copilot completion suggestions in the editor specified during the day specified.
     *
     * @return self
     */
    public function setActiveUsers($active_users)
    {
        if (is_null($active_users)) {
            throw new \InvalidArgumentException('non-nullable active_users cannot be null');
        }
        $this->container['active_users'] = $active_users;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


