<?php
/**
 * Job
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model;

use \ArrayAccess;
use \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\ObjectSerializer;

/**
 * Job Class Doc Comment
 *
 * @category Class
 * @description Information of a job execution in a workflow run
 * @package  System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Job implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'job';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'run_id' => 'int',
        'run_url' => 'string',
        'run_attempt' => 'int',
        'node_id' => 'string',
        'head_sha' => 'string',
        'url' => 'string',
        'html_url' => 'string',
        'status' => 'string',
        'conclusion' => 'string',
        'created_at' => '\DateTime',
        'started_at' => '\DateTime',
        'completed_at' => '\DateTime',
        'name' => 'string',
        'steps' => '\System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\JobStepsInner[]',
        'check_run_url' => 'string',
        'labels' => 'string[]',
        'runner_id' => 'int',
        'runner_name' => 'string',
        'runner_group_id' => 'int',
        'runner_group_name' => 'string',
        'workflow_name' => 'string',
        'head_branch' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'run_id' => null,
        'run_url' => null,
        'run_attempt' => null,
        'node_id' => null,
        'head_sha' => null,
        'url' => null,
        'html_url' => null,
        'status' => null,
        'conclusion' => null,
        'created_at' => 'date-time',
        'started_at' => 'date-time',
        'completed_at' => 'date-time',
        'name' => null,
        'steps' => null,
        'check_run_url' => null,
        'labels' => null,
        'runner_id' => null,
        'runner_name' => null,
        'runner_group_id' => null,
        'runner_group_name' => null,
        'workflow_name' => null,
        'head_branch' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'run_id' => false,
        'run_url' => false,
        'run_attempt' => false,
        'node_id' => false,
        'head_sha' => false,
        'url' => false,
        'html_url' => true,
        'status' => false,
        'conclusion' => true,
        'created_at' => false,
        'started_at' => false,
        'completed_at' => true,
        'name' => false,
        'steps' => false,
        'check_run_url' => false,
        'labels' => false,
        'runner_id' => true,
        'runner_name' => true,
        'runner_group_id' => true,
        'runner_group_name' => true,
        'workflow_name' => true,
        'head_branch' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'run_id' => 'run_id',
        'run_url' => 'run_url',
        'run_attempt' => 'run_attempt',
        'node_id' => 'node_id',
        'head_sha' => 'head_sha',
        'url' => 'url',
        'html_url' => 'html_url',
        'status' => 'status',
        'conclusion' => 'conclusion',
        'created_at' => 'created_at',
        'started_at' => 'started_at',
        'completed_at' => 'completed_at',
        'name' => 'name',
        'steps' => 'steps',
        'check_run_url' => 'check_run_url',
        'labels' => 'labels',
        'runner_id' => 'runner_id',
        'runner_name' => 'runner_name',
        'runner_group_id' => 'runner_group_id',
        'runner_group_name' => 'runner_group_name',
        'workflow_name' => 'workflow_name',
        'head_branch' => 'head_branch'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'run_id' => 'setRunId',
        'run_url' => 'setRunUrl',
        'run_attempt' => 'setRunAttempt',
        'node_id' => 'setNodeId',
        'head_sha' => 'setHeadSha',
        'url' => 'setUrl',
        'html_url' => 'setHtmlUrl',
        'status' => 'setStatus',
        'conclusion' => 'setConclusion',
        'created_at' => 'setCreatedAt',
        'started_at' => 'setStartedAt',
        'completed_at' => 'setCompletedAt',
        'name' => 'setName',
        'steps' => 'setSteps',
        'check_run_url' => 'setCheckRunUrl',
        'labels' => 'setLabels',
        'runner_id' => 'setRunnerId',
        'runner_name' => 'setRunnerName',
        'runner_group_id' => 'setRunnerGroupId',
        'runner_group_name' => 'setRunnerGroupName',
        'workflow_name' => 'setWorkflowName',
        'head_branch' => 'setHeadBranch'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'run_id' => 'getRunId',
        'run_url' => 'getRunUrl',
        'run_attempt' => 'getRunAttempt',
        'node_id' => 'getNodeId',
        'head_sha' => 'getHeadSha',
        'url' => 'getUrl',
        'html_url' => 'getHtmlUrl',
        'status' => 'getStatus',
        'conclusion' => 'getConclusion',
        'created_at' => 'getCreatedAt',
        'started_at' => 'getStartedAt',
        'completed_at' => 'getCompletedAt',
        'name' => 'getName',
        'steps' => 'getSteps',
        'check_run_url' => 'getCheckRunUrl',
        'labels' => 'getLabels',
        'runner_id' => 'getRunnerId',
        'runner_name' => 'getRunnerName',
        'runner_group_id' => 'getRunnerGroupId',
        'runner_group_name' => 'getRunnerGroupName',
        'workflow_name' => 'getWorkflowName',
        'head_branch' => 'getHeadBranch'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_QUEUED = 'queued';
    public const STATUS_IN_PROGRESS = 'in_progress';
    public const STATUS_COMPLETED = 'completed';
    public const STATUS_WAITING = 'waiting';
    public const STATUS_REQUESTED = 'requested';
    public const STATUS_PENDING = 'pending';
    public const CONCLUSION_SUCCESS = 'success';
    public const CONCLUSION_FAILURE = 'failure';
    public const CONCLUSION_NEUTRAL = 'neutral';
    public const CONCLUSION_CANCELLED = 'cancelled';
    public const CONCLUSION_SKIPPED = 'skipped';
    public const CONCLUSION_TIMED_OUT = 'timed_out';
    public const CONCLUSION_ACTION_REQUIRED = 'action_required';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_QUEUED,
            self::STATUS_IN_PROGRESS,
            self::STATUS_COMPLETED,
            self::STATUS_WAITING,
            self::STATUS_REQUESTED,
            self::STATUS_PENDING,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getConclusionAllowableValues()
    {
        return [
            self::CONCLUSION_SUCCESS,
            self::CONCLUSION_FAILURE,
            self::CONCLUSION_NEUTRAL,
            self::CONCLUSION_CANCELLED,
            self::CONCLUSION_SKIPPED,
            self::CONCLUSION_TIMED_OUT,
            self::CONCLUSION_ACTION_REQUIRED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('run_id', $data ?? [], null);
        $this->setIfExists('run_url', $data ?? [], null);
        $this->setIfExists('run_attempt', $data ?? [], null);
        $this->setIfExists('node_id', $data ?? [], null);
        $this->setIfExists('head_sha', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('html_url', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('conclusion', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('started_at', $data ?? [], null);
        $this->setIfExists('completed_at', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('steps', $data ?? [], null);
        $this->setIfExists('check_run_url', $data ?? [], null);
        $this->setIfExists('labels', $data ?? [], null);
        $this->setIfExists('runner_id', $data ?? [], null);
        $this->setIfExists('runner_name', $data ?? [], null);
        $this->setIfExists('runner_group_id', $data ?? [], null);
        $this->setIfExists('runner_group_name', $data ?? [], null);
        $this->setIfExists('workflow_name', $data ?? [], null);
        $this->setIfExists('head_branch', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['run_id'] === null) {
            $invalidProperties[] = "'run_id' can't be null";
        }
        if ($this->container['run_url'] === null) {
            $invalidProperties[] = "'run_url' can't be null";
        }
        if ($this->container['node_id'] === null) {
            $invalidProperties[] = "'node_id' can't be null";
        }
        if ($this->container['head_sha'] === null) {
            $invalidProperties[] = "'head_sha' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['html_url'] === null) {
            $invalidProperties[] = "'html_url' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['conclusion'] === null) {
            $invalidProperties[] = "'conclusion' can't be null";
        }
        $allowedValues = $this->getConclusionAllowableValues();
        if (!is_null($this->container['conclusion']) && !in_array($this->container['conclusion'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'conclusion', must be one of '%s'",
                $this->container['conclusion'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['started_at'] === null) {
            $invalidProperties[] = "'started_at' can't be null";
        }
        if ($this->container['completed_at'] === null) {
            $invalidProperties[] = "'completed_at' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['check_run_url'] === null) {
            $invalidProperties[] = "'check_run_url' can't be null";
        }
        if ($this->container['labels'] === null) {
            $invalidProperties[] = "'labels' can't be null";
        }
        if ($this->container['runner_id'] === null) {
            $invalidProperties[] = "'runner_id' can't be null";
        }
        if ($this->container['runner_name'] === null) {
            $invalidProperties[] = "'runner_name' can't be null";
        }
        if ($this->container['runner_group_id'] === null) {
            $invalidProperties[] = "'runner_group_id' can't be null";
        }
        if ($this->container['runner_group_name'] === null) {
            $invalidProperties[] = "'runner_group_name' can't be null";
        }
        if ($this->container['workflow_name'] === null) {
            $invalidProperties[] = "'workflow_name' can't be null";
        }
        if ($this->container['head_branch'] === null) {
            $invalidProperties[] = "'head_branch' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id The id of the job.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets run_id
     *
     * @return int
     */
    public function getRunId()
    {
        return $this->container['run_id'];
    }

    /**
     * Sets run_id
     *
     * @param int $run_id The id of the associated workflow run.
     *
     * @return self
     */
    public function setRunId($run_id)
    {
        if (is_null($run_id)) {
            throw new \InvalidArgumentException('non-nullable run_id cannot be null');
        }
        $this->container['run_id'] = $run_id;

        return $this;
    }

    /**
     * Gets run_url
     *
     * @return string
     */
    public function getRunUrl()
    {
        return $this->container['run_url'];
    }

    /**
     * Sets run_url
     *
     * @param string $run_url run_url
     *
     * @return self
     */
    public function setRunUrl($run_url)
    {
        if (is_null($run_url)) {
            throw new \InvalidArgumentException('non-nullable run_url cannot be null');
        }
        $this->container['run_url'] = $run_url;

        return $this;
    }

    /**
     * Gets run_attempt
     *
     * @return int|null
     */
    public function getRunAttempt()
    {
        return $this->container['run_attempt'];
    }

    /**
     * Sets run_attempt
     *
     * @param int|null $run_attempt Attempt number of the associated workflow run, 1 for first attempt and higher if the workflow was re-run.
     *
     * @return self
     */
    public function setRunAttempt($run_attempt)
    {
        if (is_null($run_attempt)) {
            throw new \InvalidArgumentException('non-nullable run_attempt cannot be null');
        }
        $this->container['run_attempt'] = $run_attempt;

        return $this;
    }

    /**
     * Gets node_id
     *
     * @return string
     */
    public function getNodeId()
    {
        return $this->container['node_id'];
    }

    /**
     * Sets node_id
     *
     * @param string $node_id node_id
     *
     * @return self
     */
    public function setNodeId($node_id)
    {
        if (is_null($node_id)) {
            throw new \InvalidArgumentException('non-nullable node_id cannot be null');
        }
        $this->container['node_id'] = $node_id;

        return $this;
    }

    /**
     * Gets head_sha
     *
     * @return string
     */
    public function getHeadSha()
    {
        return $this->container['head_sha'];
    }

    /**
     * Sets head_sha
     *
     * @param string $head_sha The SHA of the commit that is being run.
     *
     * @return self
     */
    public function setHeadSha($head_sha)
    {
        if (is_null($head_sha)) {
            throw new \InvalidArgumentException('non-nullable head_sha cannot be null');
        }
        $this->container['head_sha'] = $head_sha;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets html_url
     *
     * @return string
     */
    public function getHtmlUrl()
    {
        return $this->container['html_url'];
    }

    /**
     * Sets html_url
     *
     * @param string $html_url html_url
     *
     * @return self
     */
    public function setHtmlUrl($html_url)
    {
        if (is_null($html_url)) {
            array_push($this->openAPINullablesSetToNull, 'html_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('html_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['html_url'] = $html_url;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status The phase of the lifecycle that the job is currently in.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets conclusion
     *
     * @return string
     */
    public function getConclusion()
    {
        return $this->container['conclusion'];
    }

    /**
     * Sets conclusion
     *
     * @param string $conclusion The outcome of the job.
     *
     * @return self
     */
    public function setConclusion($conclusion)
    {
        if (is_null($conclusion)) {
            array_push($this->openAPINullablesSetToNull, 'conclusion');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('conclusion', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getConclusionAllowableValues();
        if (!is_null($conclusion) && !in_array($conclusion, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'conclusion', must be one of '%s'",
                    $conclusion,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['conclusion'] = $conclusion;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at The time that the job created, in ISO 8601 format.
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets started_at
     *
     * @return \DateTime
     */
    public function getStartedAt()
    {
        return $this->container['started_at'];
    }

    /**
     * Sets started_at
     *
     * @param \DateTime $started_at The time that the job started, in ISO 8601 format.
     *
     * @return self
     */
    public function setStartedAt($started_at)
    {
        if (is_null($started_at)) {
            throw new \InvalidArgumentException('non-nullable started_at cannot be null');
        }
        $this->container['started_at'] = $started_at;

        return $this;
    }

    /**
     * Gets completed_at
     *
     * @return \DateTime
     */
    public function getCompletedAt()
    {
        return $this->container['completed_at'];
    }

    /**
     * Sets completed_at
     *
     * @param \DateTime $completed_at The time that the job finished, in ISO 8601 format.
     *
     * @return self
     */
    public function setCompletedAt($completed_at)
    {
        if (is_null($completed_at)) {
            array_push($this->openAPINullablesSetToNull, 'completed_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('completed_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['completed_at'] = $completed_at;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The name of the job.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets steps
     *
     * @return \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\JobStepsInner[]|null
     */
    public function getSteps()
    {
        return $this->container['steps'];
    }

    /**
     * Sets steps
     *
     * @param \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\JobStepsInner[]|null $steps Steps in this job.
     *
     * @return self
     */
    public function setSteps($steps)
    {
        if (is_null($steps)) {
            throw new \InvalidArgumentException('non-nullable steps cannot be null');
        }
        $this->container['steps'] = $steps;

        return $this;
    }

    /**
     * Gets check_run_url
     *
     * @return string
     */
    public function getCheckRunUrl()
    {
        return $this->container['check_run_url'];
    }

    /**
     * Sets check_run_url
     *
     * @param string $check_run_url check_run_url
     *
     * @return self
     */
    public function setCheckRunUrl($check_run_url)
    {
        if (is_null($check_run_url)) {
            throw new \InvalidArgumentException('non-nullable check_run_url cannot be null');
        }
        $this->container['check_run_url'] = $check_run_url;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return string[]
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param string[] $labels Labels for the workflow job. Specified by the \"runs_on\" attribute in the action's workflow file.
     *
     * @return self
     */
    public function setLabels($labels)
    {
        if (is_null($labels)) {
            throw new \InvalidArgumentException('non-nullable labels cannot be null');
        }
        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets runner_id
     *
     * @return int
     */
    public function getRunnerId()
    {
        return $this->container['runner_id'];
    }

    /**
     * Sets runner_id
     *
     * @param int $runner_id The ID of the runner to which this job has been assigned. (If a runner hasn't yet been assigned, this will be null.)
     *
     * @return self
     */
    public function setRunnerId($runner_id)
    {
        if (is_null($runner_id)) {
            array_push($this->openAPINullablesSetToNull, 'runner_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('runner_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['runner_id'] = $runner_id;

        return $this;
    }

    /**
     * Gets runner_name
     *
     * @return string
     */
    public function getRunnerName()
    {
        return $this->container['runner_name'];
    }

    /**
     * Sets runner_name
     *
     * @param string $runner_name The name of the runner to which this job has been assigned. (If a runner hasn't yet been assigned, this will be null.)
     *
     * @return self
     */
    public function setRunnerName($runner_name)
    {
        if (is_null($runner_name)) {
            array_push($this->openAPINullablesSetToNull, 'runner_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('runner_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['runner_name'] = $runner_name;

        return $this;
    }

    /**
     * Gets runner_group_id
     *
     * @return int
     */
    public function getRunnerGroupId()
    {
        return $this->container['runner_group_id'];
    }

    /**
     * Sets runner_group_id
     *
     * @param int $runner_group_id The ID of the runner group to which this job has been assigned. (If a runner hasn't yet been assigned, this will be null.)
     *
     * @return self
     */
    public function setRunnerGroupId($runner_group_id)
    {
        if (is_null($runner_group_id)) {
            array_push($this->openAPINullablesSetToNull, 'runner_group_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('runner_group_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['runner_group_id'] = $runner_group_id;

        return $this;
    }

    /**
     * Gets runner_group_name
     *
     * @return string
     */
    public function getRunnerGroupName()
    {
        return $this->container['runner_group_name'];
    }

    /**
     * Sets runner_group_name
     *
     * @param string $runner_group_name The name of the runner group to which this job has been assigned. (If a runner hasn't yet been assigned, this will be null.)
     *
     * @return self
     */
    public function setRunnerGroupName($runner_group_name)
    {
        if (is_null($runner_group_name)) {
            array_push($this->openAPINullablesSetToNull, 'runner_group_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('runner_group_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['runner_group_name'] = $runner_group_name;

        return $this;
    }

    /**
     * Gets workflow_name
     *
     * @return string
     */
    public function getWorkflowName()
    {
        return $this->container['workflow_name'];
    }

    /**
     * Sets workflow_name
     *
     * @param string $workflow_name The name of the workflow.
     *
     * @return self
     */
    public function setWorkflowName($workflow_name)
    {
        if (is_null($workflow_name)) {
            array_push($this->openAPINullablesSetToNull, 'workflow_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('workflow_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['workflow_name'] = $workflow_name;

        return $this;
    }

    /**
     * Gets head_branch
     *
     * @return string
     */
    public function getHeadBranch()
    {
        return $this->container['head_branch'];
    }

    /**
     * Sets head_branch
     *
     * @param string $head_branch The name of the current branch.
     *
     * @return self
     */
    public function setHeadBranch($head_branch)
    {
        if (is_null($head_branch)) {
            array_push($this->openAPINullablesSetToNull, 'head_branch');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('head_branch', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['head_branch'] = $head_branch;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


