<?php
/**
 * PullRequestSimple
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model;

use \ArrayAccess;
use \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\ObjectSerializer;

/**
 * PullRequestSimple Class Doc Comment
 *
 * @category Class
 * @description Pull Request Simple
 * @package  System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PullRequestSimple implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'pull-request-simple';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'url' => 'string',
        'id' => 'int',
        'node_id' => 'string',
        'html_url' => 'string',
        'diff_url' => 'string',
        'patch_url' => 'string',
        'issue_url' => 'string',
        'commits_url' => 'string',
        'review_comments_url' => 'string',
        'review_comment_url' => 'string',
        'comments_url' => 'string',
        'statuses_url' => 'string',
        'number' => 'int',
        'state' => 'string',
        'locked' => 'bool',
        'title' => 'string',
        'user' => '\System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\NullableSimpleUser',
        'body' => 'string',
        'labels' => '\System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\PullRequestSimpleLabelsInner[]',
        'milestone' => '\System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\NullableMilestone',
        'active_lock_reason' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'closed_at' => '\DateTime',
        'merged_at' => '\DateTime',
        'merge_commit_sha' => 'string',
        'assignee' => '\System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\NullableSimpleUser',
        'assignees' => '\System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\SimpleUser[]',
        'requested_reviewers' => '\System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\SimpleUser[]',
        'requested_teams' => '\System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\Team[]',
        'head' => '\System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\PullRequestSimpleHead',
        'base' => '\System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\PullRequestSimpleHead',
        '_links' => '\System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\PullRequestSimpleLinks',
        'author_association' => '\System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\AuthorAssociation',
        'auto_merge' => '\System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\AutoMerge',
        'draft' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'url' => 'uri',
        'id' => null,
        'node_id' => null,
        'html_url' => 'uri',
        'diff_url' => 'uri',
        'patch_url' => 'uri',
        'issue_url' => 'uri',
        'commits_url' => 'uri',
        'review_comments_url' => 'uri',
        'review_comment_url' => null,
        'comments_url' => 'uri',
        'statuses_url' => 'uri',
        'number' => null,
        'state' => null,
        'locked' => null,
        'title' => null,
        'user' => null,
        'body' => null,
        'labels' => null,
        'milestone' => null,
        'active_lock_reason' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'closed_at' => 'date-time',
        'merged_at' => 'date-time',
        'merge_commit_sha' => null,
        'assignee' => null,
        'assignees' => null,
        'requested_reviewers' => null,
        'requested_teams' => null,
        'head' => null,
        'base' => null,
        '_links' => null,
        'author_association' => null,
        'auto_merge' => null,
        'draft' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'url' => false,
        'id' => false,
        'node_id' => false,
        'html_url' => false,
        'diff_url' => false,
        'patch_url' => false,
        'issue_url' => false,
        'commits_url' => false,
        'review_comments_url' => false,
        'review_comment_url' => false,
        'comments_url' => false,
        'statuses_url' => false,
        'number' => false,
        'state' => false,
        'locked' => false,
        'title' => false,
        'user' => true,
        'body' => true,
        'labels' => false,
        'milestone' => true,
        'active_lock_reason' => true,
        'created_at' => false,
        'updated_at' => false,
        'closed_at' => true,
        'merged_at' => true,
        'merge_commit_sha' => true,
        'assignee' => true,
        'assignees' => true,
        'requested_reviewers' => true,
        'requested_teams' => true,
        'head' => false,
        'base' => false,
        '_links' => false,
        'author_association' => false,
        'auto_merge' => true,
        'draft' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'url' => 'url',
        'id' => 'id',
        'node_id' => 'node_id',
        'html_url' => 'html_url',
        'diff_url' => 'diff_url',
        'patch_url' => 'patch_url',
        'issue_url' => 'issue_url',
        'commits_url' => 'commits_url',
        'review_comments_url' => 'review_comments_url',
        'review_comment_url' => 'review_comment_url',
        'comments_url' => 'comments_url',
        'statuses_url' => 'statuses_url',
        'number' => 'number',
        'state' => 'state',
        'locked' => 'locked',
        'title' => 'title',
        'user' => 'user',
        'body' => 'body',
        'labels' => 'labels',
        'milestone' => 'milestone',
        'active_lock_reason' => 'active_lock_reason',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at',
        'closed_at' => 'closed_at',
        'merged_at' => 'merged_at',
        'merge_commit_sha' => 'merge_commit_sha',
        'assignee' => 'assignee',
        'assignees' => 'assignees',
        'requested_reviewers' => 'requested_reviewers',
        'requested_teams' => 'requested_teams',
        'head' => 'head',
        'base' => 'base',
        '_links' => '_links',
        'author_association' => 'author_association',
        'auto_merge' => 'auto_merge',
        'draft' => 'draft'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'url' => 'setUrl',
        'id' => 'setId',
        'node_id' => 'setNodeId',
        'html_url' => 'setHtmlUrl',
        'diff_url' => 'setDiffUrl',
        'patch_url' => 'setPatchUrl',
        'issue_url' => 'setIssueUrl',
        'commits_url' => 'setCommitsUrl',
        'review_comments_url' => 'setReviewCommentsUrl',
        'review_comment_url' => 'setReviewCommentUrl',
        'comments_url' => 'setCommentsUrl',
        'statuses_url' => 'setStatusesUrl',
        'number' => 'setNumber',
        'state' => 'setState',
        'locked' => 'setLocked',
        'title' => 'setTitle',
        'user' => 'setUser',
        'body' => 'setBody',
        'labels' => 'setLabels',
        'milestone' => 'setMilestone',
        'active_lock_reason' => 'setActiveLockReason',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'closed_at' => 'setClosedAt',
        'merged_at' => 'setMergedAt',
        'merge_commit_sha' => 'setMergeCommitSha',
        'assignee' => 'setAssignee',
        'assignees' => 'setAssignees',
        'requested_reviewers' => 'setRequestedReviewers',
        'requested_teams' => 'setRequestedTeams',
        'head' => 'setHead',
        'base' => 'setBase',
        '_links' => 'setLinks',
        'author_association' => 'setAuthorAssociation',
        'auto_merge' => 'setAutoMerge',
        'draft' => 'setDraft'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'url' => 'getUrl',
        'id' => 'getId',
        'node_id' => 'getNodeId',
        'html_url' => 'getHtmlUrl',
        'diff_url' => 'getDiffUrl',
        'patch_url' => 'getPatchUrl',
        'issue_url' => 'getIssueUrl',
        'commits_url' => 'getCommitsUrl',
        'review_comments_url' => 'getReviewCommentsUrl',
        'review_comment_url' => 'getReviewCommentUrl',
        'comments_url' => 'getCommentsUrl',
        'statuses_url' => 'getStatusesUrl',
        'number' => 'getNumber',
        'state' => 'getState',
        'locked' => 'getLocked',
        'title' => 'getTitle',
        'user' => 'getUser',
        'body' => 'getBody',
        'labels' => 'getLabels',
        'milestone' => 'getMilestone',
        'active_lock_reason' => 'getActiveLockReason',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'closed_at' => 'getClosedAt',
        'merged_at' => 'getMergedAt',
        'merge_commit_sha' => 'getMergeCommitSha',
        'assignee' => 'getAssignee',
        'assignees' => 'getAssignees',
        'requested_reviewers' => 'getRequestedReviewers',
        'requested_teams' => 'getRequestedTeams',
        'head' => 'getHead',
        'base' => 'getBase',
        '_links' => 'getLinks',
        'author_association' => 'getAuthorAssociation',
        'auto_merge' => 'getAutoMerge',
        'draft' => 'getDraft'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('node_id', $data ?? [], null);
        $this->setIfExists('html_url', $data ?? [], null);
        $this->setIfExists('diff_url', $data ?? [], null);
        $this->setIfExists('patch_url', $data ?? [], null);
        $this->setIfExists('issue_url', $data ?? [], null);
        $this->setIfExists('commits_url', $data ?? [], null);
        $this->setIfExists('review_comments_url', $data ?? [], null);
        $this->setIfExists('review_comment_url', $data ?? [], null);
        $this->setIfExists('comments_url', $data ?? [], null);
        $this->setIfExists('statuses_url', $data ?? [], null);
        $this->setIfExists('number', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('locked', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('user', $data ?? [], null);
        $this->setIfExists('body', $data ?? [], null);
        $this->setIfExists('labels', $data ?? [], null);
        $this->setIfExists('milestone', $data ?? [], null);
        $this->setIfExists('active_lock_reason', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('closed_at', $data ?? [], null);
        $this->setIfExists('merged_at', $data ?? [], null);
        $this->setIfExists('merge_commit_sha', $data ?? [], null);
        $this->setIfExists('assignee', $data ?? [], null);
        $this->setIfExists('assignees', $data ?? [], null);
        $this->setIfExists('requested_reviewers', $data ?? [], null);
        $this->setIfExists('requested_teams', $data ?? [], null);
        $this->setIfExists('head', $data ?? [], null);
        $this->setIfExists('base', $data ?? [], null);
        $this->setIfExists('_links', $data ?? [], null);
        $this->setIfExists('author_association', $data ?? [], null);
        $this->setIfExists('auto_merge', $data ?? [], null);
        $this->setIfExists('draft', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['node_id'] === null) {
            $invalidProperties[] = "'node_id' can't be null";
        }
        if ($this->container['html_url'] === null) {
            $invalidProperties[] = "'html_url' can't be null";
        }
        if ($this->container['diff_url'] === null) {
            $invalidProperties[] = "'diff_url' can't be null";
        }
        if ($this->container['patch_url'] === null) {
            $invalidProperties[] = "'patch_url' can't be null";
        }
        if ($this->container['issue_url'] === null) {
            $invalidProperties[] = "'issue_url' can't be null";
        }
        if ($this->container['commits_url'] === null) {
            $invalidProperties[] = "'commits_url' can't be null";
        }
        if ($this->container['review_comments_url'] === null) {
            $invalidProperties[] = "'review_comments_url' can't be null";
        }
        if ($this->container['review_comment_url'] === null) {
            $invalidProperties[] = "'review_comment_url' can't be null";
        }
        if ($this->container['comments_url'] === null) {
            $invalidProperties[] = "'comments_url' can't be null";
        }
        if ($this->container['statuses_url'] === null) {
            $invalidProperties[] = "'statuses_url' can't be null";
        }
        if ($this->container['number'] === null) {
            $invalidProperties[] = "'number' can't be null";
        }
        if ($this->container['state'] === null) {
            $invalidProperties[] = "'state' can't be null";
        }
        if ($this->container['locked'] === null) {
            $invalidProperties[] = "'locked' can't be null";
        }
        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['user'] === null) {
            $invalidProperties[] = "'user' can't be null";
        }
        if ($this->container['body'] === null) {
            $invalidProperties[] = "'body' can't be null";
        }
        if ($this->container['labels'] === null) {
            $invalidProperties[] = "'labels' can't be null";
        }
        if ($this->container['milestone'] === null) {
            $invalidProperties[] = "'milestone' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        if ($this->container['closed_at'] === null) {
            $invalidProperties[] = "'closed_at' can't be null";
        }
        if ($this->container['merged_at'] === null) {
            $invalidProperties[] = "'merged_at' can't be null";
        }
        if ($this->container['merge_commit_sha'] === null) {
            $invalidProperties[] = "'merge_commit_sha' can't be null";
        }
        if ($this->container['assignee'] === null) {
            $invalidProperties[] = "'assignee' can't be null";
        }
        if ($this->container['head'] === null) {
            $invalidProperties[] = "'head' can't be null";
        }
        if ($this->container['base'] === null) {
            $invalidProperties[] = "'base' can't be null";
        }
        if ($this->container['_links'] === null) {
            $invalidProperties[] = "'_links' can't be null";
        }
        if ($this->container['author_association'] === null) {
            $invalidProperties[] = "'author_association' can't be null";
        }
        if ($this->container['auto_merge'] === null) {
            $invalidProperties[] = "'auto_merge' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets node_id
     *
     * @return string
     */
    public function getNodeId()
    {
        return $this->container['node_id'];
    }

    /**
     * Sets node_id
     *
     * @param string $node_id node_id
     *
     * @return self
     */
    public function setNodeId($node_id)
    {
        if (is_null($node_id)) {
            throw new \InvalidArgumentException('non-nullable node_id cannot be null');
        }
        $this->container['node_id'] = $node_id;

        return $this;
    }

    /**
     * Gets html_url
     *
     * @return string
     */
    public function getHtmlUrl()
    {
        return $this->container['html_url'];
    }

    /**
     * Sets html_url
     *
     * @param string $html_url html_url
     *
     * @return self
     */
    public function setHtmlUrl($html_url)
    {
        if (is_null($html_url)) {
            throw new \InvalidArgumentException('non-nullable html_url cannot be null');
        }
        $this->container['html_url'] = $html_url;

        return $this;
    }

    /**
     * Gets diff_url
     *
     * @return string
     */
    public function getDiffUrl()
    {
        return $this->container['diff_url'];
    }

    /**
     * Sets diff_url
     *
     * @param string $diff_url diff_url
     *
     * @return self
     */
    public function setDiffUrl($diff_url)
    {
        if (is_null($diff_url)) {
            throw new \InvalidArgumentException('non-nullable diff_url cannot be null');
        }
        $this->container['diff_url'] = $diff_url;

        return $this;
    }

    /**
     * Gets patch_url
     *
     * @return string
     */
    public function getPatchUrl()
    {
        return $this->container['patch_url'];
    }

    /**
     * Sets patch_url
     *
     * @param string $patch_url patch_url
     *
     * @return self
     */
    public function setPatchUrl($patch_url)
    {
        if (is_null($patch_url)) {
            throw new \InvalidArgumentException('non-nullable patch_url cannot be null');
        }
        $this->container['patch_url'] = $patch_url;

        return $this;
    }

    /**
     * Gets issue_url
     *
     * @return string
     */
    public function getIssueUrl()
    {
        return $this->container['issue_url'];
    }

    /**
     * Sets issue_url
     *
     * @param string $issue_url issue_url
     *
     * @return self
     */
    public function setIssueUrl($issue_url)
    {
        if (is_null($issue_url)) {
            throw new \InvalidArgumentException('non-nullable issue_url cannot be null');
        }
        $this->container['issue_url'] = $issue_url;

        return $this;
    }

    /**
     * Gets commits_url
     *
     * @return string
     */
    public function getCommitsUrl()
    {
        return $this->container['commits_url'];
    }

    /**
     * Sets commits_url
     *
     * @param string $commits_url commits_url
     *
     * @return self
     */
    public function setCommitsUrl($commits_url)
    {
        if (is_null($commits_url)) {
            throw new \InvalidArgumentException('non-nullable commits_url cannot be null');
        }
        $this->container['commits_url'] = $commits_url;

        return $this;
    }

    /**
     * Gets review_comments_url
     *
     * @return string
     */
    public function getReviewCommentsUrl()
    {
        return $this->container['review_comments_url'];
    }

    /**
     * Sets review_comments_url
     *
     * @param string $review_comments_url review_comments_url
     *
     * @return self
     */
    public function setReviewCommentsUrl($review_comments_url)
    {
        if (is_null($review_comments_url)) {
            throw new \InvalidArgumentException('non-nullable review_comments_url cannot be null');
        }
        $this->container['review_comments_url'] = $review_comments_url;

        return $this;
    }

    /**
     * Gets review_comment_url
     *
     * @return string
     */
    public function getReviewCommentUrl()
    {
        return $this->container['review_comment_url'];
    }

    /**
     * Sets review_comment_url
     *
     * @param string $review_comment_url review_comment_url
     *
     * @return self
     */
    public function setReviewCommentUrl($review_comment_url)
    {
        if (is_null($review_comment_url)) {
            throw new \InvalidArgumentException('non-nullable review_comment_url cannot be null');
        }
        $this->container['review_comment_url'] = $review_comment_url;

        return $this;
    }

    /**
     * Gets comments_url
     *
     * @return string
     */
    public function getCommentsUrl()
    {
        return $this->container['comments_url'];
    }

    /**
     * Sets comments_url
     *
     * @param string $comments_url comments_url
     *
     * @return self
     */
    public function setCommentsUrl($comments_url)
    {
        if (is_null($comments_url)) {
            throw new \InvalidArgumentException('non-nullable comments_url cannot be null');
        }
        $this->container['comments_url'] = $comments_url;

        return $this;
    }

    /**
     * Gets statuses_url
     *
     * @return string
     */
    public function getStatusesUrl()
    {
        return $this->container['statuses_url'];
    }

    /**
     * Sets statuses_url
     *
     * @param string $statuses_url statuses_url
     *
     * @return self
     */
    public function setStatusesUrl($statuses_url)
    {
        if (is_null($statuses_url)) {
            throw new \InvalidArgumentException('non-nullable statuses_url cannot be null');
        }
        $this->container['statuses_url'] = $statuses_url;

        return $this;
    }

    /**
     * Gets number
     *
     * @return int
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param int $number number
     *
     * @return self
     */
    public function setNumber($number)
    {
        if (is_null($number)) {
            throw new \InvalidArgumentException('non-nullable number cannot be null');
        }
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string $state state
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            throw new \InvalidArgumentException('non-nullable state cannot be null');
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets locked
     *
     * @return bool
     */
    public function getLocked()
    {
        return $this->container['locked'];
    }

    /**
     * Sets locked
     *
     * @param bool $locked locked
     *
     * @return self
     */
    public function setLocked($locked)
    {
        if (is_null($locked)) {
            throw new \InvalidArgumentException('non-nullable locked cannot be null');
        }
        $this->container['locked'] = $locked;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets user
     *
     * @return \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\NullableSimpleUser
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\NullableSimpleUser $user user
     *
     * @return self
     */
    public function setUser($user)
    {
        if (is_null($user)) {
            array_push($this->openAPINullablesSetToNull, 'user');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets body
     *
     * @return string
     */
    public function getBody()
    {
        return $this->container['body'];
    }

    /**
     * Sets body
     *
     * @param string $body body
     *
     * @return self
     */
    public function setBody($body)
    {
        if (is_null($body)) {
            array_push($this->openAPINullablesSetToNull, 'body');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('body', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['body'] = $body;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\PullRequestSimpleLabelsInner[]
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\PullRequestSimpleLabelsInner[] $labels labels
     *
     * @return self
     */
    public function setLabels($labels)
    {
        if (is_null($labels)) {
            throw new \InvalidArgumentException('non-nullable labels cannot be null');
        }
        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets milestone
     *
     * @return \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\NullableMilestone
     */
    public function getMilestone()
    {
        return $this->container['milestone'];
    }

    /**
     * Sets milestone
     *
     * @param \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\NullableMilestone $milestone milestone
     *
     * @return self
     */
    public function setMilestone($milestone)
    {
        if (is_null($milestone)) {
            array_push($this->openAPINullablesSetToNull, 'milestone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('milestone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['milestone'] = $milestone;

        return $this;
    }

    /**
     * Gets active_lock_reason
     *
     * @return string|null
     */
    public function getActiveLockReason()
    {
        return $this->container['active_lock_reason'];
    }

    /**
     * Sets active_lock_reason
     *
     * @param string|null $active_lock_reason active_lock_reason
     *
     * @return self
     */
    public function setActiveLockReason($active_lock_reason)
    {
        if (is_null($active_lock_reason)) {
            array_push($this->openAPINullablesSetToNull, 'active_lock_reason');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('active_lock_reason', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['active_lock_reason'] = $active_lock_reason;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets closed_at
     *
     * @return \DateTime
     */
    public function getClosedAt()
    {
        return $this->container['closed_at'];
    }

    /**
     * Sets closed_at
     *
     * @param \DateTime $closed_at closed_at
     *
     * @return self
     */
    public function setClosedAt($closed_at)
    {
        if (is_null($closed_at)) {
            array_push($this->openAPINullablesSetToNull, 'closed_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('closed_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['closed_at'] = $closed_at;

        return $this;
    }

    /**
     * Gets merged_at
     *
     * @return \DateTime
     */
    public function getMergedAt()
    {
        return $this->container['merged_at'];
    }

    /**
     * Sets merged_at
     *
     * @param \DateTime $merged_at merged_at
     *
     * @return self
     */
    public function setMergedAt($merged_at)
    {
        if (is_null($merged_at)) {
            array_push($this->openAPINullablesSetToNull, 'merged_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('merged_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['merged_at'] = $merged_at;

        return $this;
    }

    /**
     * Gets merge_commit_sha
     *
     * @return string
     */
    public function getMergeCommitSha()
    {
        return $this->container['merge_commit_sha'];
    }

    /**
     * Sets merge_commit_sha
     *
     * @param string $merge_commit_sha merge_commit_sha
     *
     * @return self
     */
    public function setMergeCommitSha($merge_commit_sha)
    {
        if (is_null($merge_commit_sha)) {
            array_push($this->openAPINullablesSetToNull, 'merge_commit_sha');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('merge_commit_sha', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['merge_commit_sha'] = $merge_commit_sha;

        return $this;
    }

    /**
     * Gets assignee
     *
     * @return \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\NullableSimpleUser
     */
    public function getAssignee()
    {
        return $this->container['assignee'];
    }

    /**
     * Sets assignee
     *
     * @param \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\NullableSimpleUser $assignee assignee
     *
     * @return self
     */
    public function setAssignee($assignee)
    {
        if (is_null($assignee)) {
            array_push($this->openAPINullablesSetToNull, 'assignee');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('assignee', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['assignee'] = $assignee;

        return $this;
    }

    /**
     * Gets assignees
     *
     * @return \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\SimpleUser[]|null
     */
    public function getAssignees()
    {
        return $this->container['assignees'];
    }

    /**
     * Sets assignees
     *
     * @param \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\SimpleUser[]|null $assignees assignees
     *
     * @return self
     */
    public function setAssignees($assignees)
    {
        if (is_null($assignees)) {
            array_push($this->openAPINullablesSetToNull, 'assignees');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('assignees', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['assignees'] = $assignees;

        return $this;
    }

    /**
     * Gets requested_reviewers
     *
     * @return \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\SimpleUser[]|null
     */
    public function getRequestedReviewers()
    {
        return $this->container['requested_reviewers'];
    }

    /**
     * Sets requested_reviewers
     *
     * @param \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\SimpleUser[]|null $requested_reviewers requested_reviewers
     *
     * @return self
     */
    public function setRequestedReviewers($requested_reviewers)
    {
        if (is_null($requested_reviewers)) {
            array_push($this->openAPINullablesSetToNull, 'requested_reviewers');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('requested_reviewers', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['requested_reviewers'] = $requested_reviewers;

        return $this;
    }

    /**
     * Gets requested_teams
     *
     * @return \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\Team[]|null
     */
    public function getRequestedTeams()
    {
        return $this->container['requested_teams'];
    }

    /**
     * Sets requested_teams
     *
     * @param \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\Team[]|null $requested_teams requested_teams
     *
     * @return self
     */
    public function setRequestedTeams($requested_teams)
    {
        if (is_null($requested_teams)) {
            array_push($this->openAPINullablesSetToNull, 'requested_teams');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('requested_teams', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['requested_teams'] = $requested_teams;

        return $this;
    }

    /**
     * Gets head
     *
     * @return \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\PullRequestSimpleHead
     */
    public function getHead()
    {
        return $this->container['head'];
    }

    /**
     * Sets head
     *
     * @param \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\PullRequestSimpleHead $head head
     *
     * @return self
     */
    public function setHead($head)
    {
        if (is_null($head)) {
            throw new \InvalidArgumentException('non-nullable head cannot be null');
        }
        $this->container['head'] = $head;

        return $this;
    }

    /**
     * Gets base
     *
     * @return \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\PullRequestSimpleHead
     */
    public function getBase()
    {
        return $this->container['base'];
    }

    /**
     * Sets base
     *
     * @param \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\PullRequestSimpleHead $base base
     *
     * @return self
     */
    public function setBase($base)
    {
        if (is_null($base)) {
            throw new \InvalidArgumentException('non-nullable base cannot be null');
        }
        $this->container['base'] = $base;

        return $this;
    }

    /**
     * Gets _links
     *
     * @return \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\PullRequestSimpleLinks
     */
    public function getLinks()
    {
        return $this->container['_links'];
    }

    /**
     * Sets _links
     *
     * @param \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\PullRequestSimpleLinks $_links _links
     *
     * @return self
     */
    public function setLinks($_links)
    {
        if (is_null($_links)) {
            throw new \InvalidArgumentException('non-nullable _links cannot be null');
        }
        $this->container['_links'] = $_links;

        return $this;
    }

    /**
     * Gets author_association
     *
     * @return \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\AuthorAssociation
     */
    public function getAuthorAssociation()
    {
        return $this->container['author_association'];
    }

    /**
     * Sets author_association
     *
     * @param \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\AuthorAssociation $author_association author_association
     *
     * @return self
     */
    public function setAuthorAssociation($author_association)
    {
        if (is_null($author_association)) {
            throw new \InvalidArgumentException('non-nullable author_association cannot be null');
        }
        $this->container['author_association'] = $author_association;

        return $this;
    }

    /**
     * Gets auto_merge
     *
     * @return \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\AutoMerge
     */
    public function getAutoMerge()
    {
        return $this->container['auto_merge'];
    }

    /**
     * Sets auto_merge
     *
     * @param \System\Base\Providers\BasepackagesServiceProvider\Packages\ApiClientServices\Apis\Repos\Github\Model\AutoMerge $auto_merge auto_merge
     *
     * @return self
     */
    public function setAutoMerge($auto_merge)
    {
        if (is_null($auto_merge)) {
            array_push($this->openAPINullablesSetToNull, 'auto_merge');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('auto_merge', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['auto_merge'] = $auto_merge;

        return $this;
    }

    /**
     * Gets draft
     *
     * @return bool|null
     */
    public function getDraft()
    {
        return $this->container['draft'];
    }

    /**
     * Sets draft
     *
     * @param bool|null $draft Indicates whether or not the pull request is a draft.
     *
     * @return self
     */
    public function setDraft($draft)
    {
        if (is_null($draft)) {
            throw new \InvalidArgumentException('non-nullable draft cannot be null');
        }
        $this->container['draft'] = $draft;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


