<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Bazaari Framework Core Setup</title>
        <link rel="stylesheet" type="text/css" href="/core/default/css/core.css">
        <link rel="stylesheet" type="text/css" href="/core/default/css/plugins.css">
        <script src="/core/default/js/header/jsHeaderDependencies.js"></script>
        <script src="/core/default/js/header/jsHeaderCore.js"></script>
        <script src="/core/default/js/header/jsHeaderPlugins.js"></script>
    </head>
    <body>
        <script type="text/javascript" charset="utf-8">
            if (!window.dataCollection) {
                window.dataCollection = { };
                dataCollection = window.dataCollection;
                dataCollection.env = { };
                dataCollection.env.sounds = { };
                dataCollection.env.httpScheme = '<?php echo $request->getScheme(); ?>';
                dataCollection.env.httpHost = '<?php echo $request->getHttpHost(); ?>';
                dataCollection.env.rootPath = '<?php echo $request->getScheme(); ?>://<?php echo $request->getHttpHost(); ?>/';
                dataCollection.env.libsLoaded = false;
            }
        </script>
        <div class="main-content">
            <div class="container-fluid">
                <input id="session-token" type="hidden" value="<?php echo $session->getId(); ?>" />
                <div class="row">
                    <div class="col">
                        <?php if (!$onlyUpdateDb) { ?>
                            <div id="alert" class="alert mt-2 mb-2" hidden></div>
                        <?php } else { ?>
                            <div id="alert" class="alert mt-2 mb-2 alert-danger"><?php echo $message . ". Please update database details or fix your database server."; ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="card mt-2 mb-2">
                            <form autocomplete="off">
                                <?php if ($onlyUpdateDb) { ?>
                                    <div class="card-header bg-primary text-white text-center font-weight-bold text-uppercase rounded-0">Bazaari Framework Database Update</div>
                                <?php } else { ?>
                                    <div class="card-header bg-primary text-white text-center font-weight-bold text-uppercase rounded-0">Bazaari Framework Core Setup</div>
                                <?php } ?>
                                <div class="card-body bg-white">
                                    <?php if (!$precheckFail) { ?>
                                        <div class="row vdivide justify-content-center">
                                            <div class="col-6 p-3">
                                                <legend class="text-uppercase">Database</legend>
                                                <div class="row">
                                                    <div class="col">
                                                        <div class="form-group">
                                                            <label class="text-uppercase text-xs" for="host">Select Database Type *</label>
                                                            <select class="custom-select rounded-0 input-xs" style="padding: 0.375rem 1.75rem 0.375rem 0.75rem;" id="databasetype">
                                                                <option value="hybrid" selected="">Flat File + MySQL (Recommended)</option>
                                                                <option value="ff">Flat File Only</option>
                                                                <option value="db">MySQL Only</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div id="mysql">
                                                    <div class="row">
                                                        <div class="col">
                                                            <div class="form-group">
                                                                <label class="text-uppercase text-xs" for="host">Host *</label>
                                                                <div class="input-group input-group-sm">
                                                                    <input type="text" name="host" id="host" class="form-control rounded-0" value="localhost">
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col">
                                                            <div class="form-group">
                                                                <label class="text-uppercase text-xs" for="port">Port *</label>
                                                                <div class="input-group input-group-sm">
                                                                    <input type="text" name="port" id="port" class="form-control rounded-0" value="3306">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col">
                                                            <div class="form-group">
                                                                <label class="text-uppercase text-xs" for="dbname">Database Name *</label>
                                                                <div class="input-group input-group-sm">
                                                                    <input type="text" name="dbname" id="dbname" class="form-control rounded-0" value="sp">
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col">
                                                            <div class="form-group">
                                                                <label class="text-uppercase text-xs" for="charset">Database Charset *</label>
                                                                <div class="input-group input-group-sm">
                                                                    <input type="text" name="charset" id="charset" class="form-control rounded-0" value="utf8mb4">
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col">
                                                            <div class="form-group">
                                                                <label class="text-uppercase text-xs" for="collation">Database Collation *</label>
                                                                <div class="input-group input-group-sm">
                                                                    <input type="text" name="collation" id="collation" class="form-control rounded-0" value="utf8mb4_general_ci">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col">
                                                            <div class="form-group">
                                                                <label class="text-uppercase text-xs" for="username">Database Username *</label>
                                                                <div class="input-group input-group-sm">
                                                                    <input type="text" name="username" id="username" class="form-control rounded-0" value="sp">
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col">
                                                            <div class="form-group mb-0">
                                                                <label class="text-uppercase text-xs" for="password">Database Password *</label>
                                                                <div class="input-group input-group-sm">
                                                                    <div class="input-group-prepend">
                                                                        <button class="btn btn-sm btn-primary rounded-0" id="generate_db_password_button" data-toggle="tooltip" data-html="true" data-placement="auto" title="" role="button" data-original-title="">
                                                                            <i class="fas fa-fw fa-cog fa-spin" hidden=""></i> <i class="fas fa-fw fa-wand-magic-sparkles"></i>
                                                                        </button>
                                                                    </div>
                                                                    <input type="password" name="password" id="password" class="form-control rounded-0">
                                                                    <div class="input-group-append">
                                                                        <button id="password-visibility" class="btn btn-primary rounded-0" type="button" data-toggle="tooltip" data-html="true" data-placement="auto" title="" data-original-title="">
                                                                            <i class="fas fa-fw fa-eye-slash"></i>
                                                                        </button>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="form-group">
                                                                <div id="db_password_strength_meter"></div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <?php if (!$onlyUpdateDb) { ?>
                                                        <div class="row">
                                                            <div class="col">
                                                                <div class="form-group">
                                                                    <div class="checkbox icheck-danger">
                                                                        <input type="checkbox" name="drop" id="drop">
                                                                        <label class="text-uppercase text-xs" for="drop">
                                                                            Drop tables if exists
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="col">
                                                                <div class="form-group">
                                                                    <div class="checkbox icheck-success">
                                                                        <input type="checkbox" name="create" id="create">
                                                                        <label class="text-uppercase text-xs" for="create">
                                                                            Create new database
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="col">
                                                                <div class="form-group">
                                                                    <div class="checkbox icheck-success">
                                                                        <input type="checkbox" name="create-grant" id="create-grant">
                                                                        <label class="text-uppercase text-xs" for="create-grant">
                                                                            Create new user/grant permissions
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row" id="create-user">
                                                            <div class="col">
                                                                <div class="form-group">
                                                                    <label class="text-uppercase text-xs" for="create-username">Database Username (With create permission) *</label>
                                                                    <div class="input-group input-group-sm">
                                                                        <input type="text" name="create-username" id="create-username" class="form-control rounded-0" disabled>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="col">
                                                                <div class="form-group">
                                                                    <label class="text-uppercase text-xs" for="create-password">Database Password (With create permission) *</label>
                                                                    <div class="input-group input-group-sm">
                                                                        <input type="password" name="create-password" id="create-password" class="form-control rounded-0" disabled>
                                                                        <div class="input-group-append">
                                                                            <button id="create-password-visibility" class="btn btn-primary rounded-0" type="button" data-toggle="tooltip" data-html="true" data-placement="auto" title="" data-original-title="">
                                                                                <i class="fas fa-fw fa-eye-slash"></i>
                                                                            </button>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                            <?php if (!$onlyUpdateDb) { ?>
                                                <div class="col-6 p-3">
                                                    <legend class="text-uppercase">Admin Account</legend>
                                                    <div class="row">
                                                        <div class="col">
                                                            <div class="form-group">
                                                                <label class="text-uppercase text-xs" for="email">Email *</label>
                                                                <div class="input-group input-group-sm">
                                                                    <input type="text" name="email" id="email" class="form-control rounded-0">
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col">
                                                            <div class="form-group mb-0">
                                                                <label class="text-uppercase text-xs" for="pass">Password *</label>
                                                                <div class="input-group input-group-sm">
                                                                    <div class="input-group-prepend">
                                                                        <button class="btn btn-sm btn-primary rounded-0" id="generate_user_password_button" data-toggle="tooltip" data-html="true" data-placement="auto" title="" role="button" data-original-title="">
                                                                            <i class="fas fa-fw fa-cog fa-spin" hidden=""></i> <i class="fas fa-fw fa-wand-magic-sparkles"></i>
                                                                        </button>
                                                                    </div>
                                                                    <input type="password" name="pass" id="pass" class="form-control rounded-0">
                                                                    <div class="input-group-append">
                                                                        <button id="pass-visibility" class="btn btn-primary rounded-0" type="button" data-toggle="tooltip" data-html="true" data-placement="auto" title="" data-original-title="">
                                                                            <i class="fas fa-fw fa-eye-slash"></i>
                                                                        </button>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="form-group">
                                                                <div id="user_password_strength_meter"></div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <legend class="text-uppercase">Geo Location</legend>
                                                    <div class="row">
                                                        <div class="col">
                                                            <div class="form-group">
                                                                <select class="custom-select rounded-0" style="padding: 0.375rem 1.75rem 0.375rem 0.75rem;" id="country">
                                                                    <?php foreach ($countries as $key => $value) {
                                                                        $selected = '';

                                                                        if ($value['iso3'] === 'AUS') {
                                                                            $selected = 'selected=""';
                                                                        }

                                                                        echo '<option value="' . $value['iso3'] . '"' . $selected . '>' . $value['name'] . '</option>';
                                                                    } ?>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="col">
                                                            <div class="form-group">
                                                                <div class="checkbox icheck-danger">
                                                                    <input type="checkbox" name="ip2location" id="ip2location">
                                                                    <label class="text-uppercase text-xs" for="ip2location">
                                                                        Install ip2location database?
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <small class="text-danger">Note: Depending on ip database, ip2location database can take several minutes to install.</small>
                                                    <legend class="text-uppercase mt-3">Security</legend>
                                                    <div class="row">
                                                        <div class="col">
                                                            <div class="form-group">
                                                                <label class="text-uppercase text-xs" for="pwf">Password Encryption Level *</label>
                                                                <div class="input-group input-group-sm">
                                                                    <input type="number" min="4" max="16" name="pwf" id="pwf" class="form-control rounded-0" value="8" disabled>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col">
                                                            <div class="form-group">
                                                                <label class="text-uppercase text-xs" for="cwf">Cookies Encryption Level *</label>
                                                                <div class="input-group input-group-sm">
                                                                    <input type="number" min="4" max="16" name="cwf" id="cwf" class="form-control rounded-0" value="8" disabled>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col">
                                                            <div class="form-group mb-2">
                                                                <div class="checkbox icheck-success">
                                                                    <input type="checkbox" name="auto-encrypt-level" id="auto-encrypt-level" checked>
                                                                    <label class="text-uppercase text-xs" for="auto-encrypt-level">
                                                                        Calculate level as per system configuration
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <small class="text-danger">Note: Higher the number, better the security but, slower the performance. Range: 4-16</small>
                                                    <legend class="mt-3">Development</legend>
                                                    <div class="row">
                                                        <div class="col">
                                                            <div class="form-group">
                                                                <div class="checkbox icheck-warning">
                                                                    <input type="checkbox" name="dev" id="dev">
                                                                    <label class="text-uppercase text-xs" for="dev">
                                                                        Dev Mode?
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                    <?php if ($precheckFail) { ?>
                                        <div class="row vdivide justify-content-center">
                                            <?php if ($responseCode == '1') { ?>
                                                <div class="col">
                                                    <span class="text-danger"><?php echo $responseMessage; ?></span>
                                                </div>
                                            <?php } else { ?>
                                                <div class="col">
                                                    Bazaari Framework requires some external dependencies which are not available on this system. You can either install those dependencies using CLI if you have access to the server using the command <span class="text-info">./composer install"</span> in the <span class="text-info">external/ folder</span>. That will install the required dependencies and you can then run this setup again.<br><br>
                                                    If in case you do not have access to the server via CLI, you can click "Download & Install Dependencies" button and the framework will try and install the files for you.
                                                </div>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                    <hr>
                                    <div id="installer-progress" class="mb-3" hidden></div>
                                    <div class="row text-center p-3">
                                        <?php if (!$onlyUpdateDb) { ?>
                                            <?php if (!$precheckFail) { ?>
                                                <div class="col" id="submit-div">
                                                    <button id="submit" class="btn btn-primary">
                                                        <i id="submit-spinner" class="fa fa-cog fa-spin" hidden></i>
                                                            Setup
                                                        </button>
                                                    </div>
                                            <?php } else { ?>
                                                <?php if ($responseCode != '1') { ?>
                                                    <div class="col" id="submit-div">
                                                        <button id="submit" class="btn btn-primary">
                                                            <i id="submit-spinner" class="fa fa-cog fa-spin" hidden></i>
                                                                Download & Install Dependencies
                                                        </button>
                                                    </div>
                                                <?php } ?>
                                            <?php } ?>
                                        <?php } else { ?>
                                            <div class="col" id="update-div">
                                                <button id="update" class="btn btn-primary">
                                                    <i id="update-spinner" class="fa fa-cog fa-spin" hidden></i>
                                                    Update
                                                </button>
                                            </div>
                                        <?php } ?>
                                        <?php if (!$precheckFail) { ?>
                                            <div class="col" id="access-div" hidden>
                                                <a href='/' id="access" class="btn" disabled=""><i class="fa"></i> Access Core</a>
                                            </div>
                                        <?php } else { ?>
                                            <div class="col" id="access-div" hidden>
                                                <a href='/' id="access" class="btn" disabled="">Run Setup</a>
                                            </div>
                                        <?php } ?>
                                    </div>
                                    <div class="row">
                                        <div class="col" id="external-div" hidden>
                                            <div class="form-group">
                                                <label class="text-uppercase text-xs" for="username">External Package Installer Logs</label>
                                                <textarea id="external-data" class="form-control form-control-sm rounded-0" rows="10" disabled>Downloading & installing external packages...</textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <footer class="footer text-center m-2">
            Copyright © <strong><a target="_blank" href="https://www.bazaari.com.au/">Bazaari E Trade Pty Ltd.</a></strong> 2014-<?php echo date("Y"); ?> All rights reserved.
            <script src="/core/default/js/footer/jsFooterDependencies.js"></script>
            <script src="/core/default/js/footer/jsFooterCore.js"></script>
            <script src="/core/default/js/footer/jsFooterPlugins.js"></script>
        </footer>
        <script type="text/javascript">
            <?php if ($precheckFail) { ?>
                BazProgress.buildProgressBar($('#installer-progress'), true);
            <?php } else { ?>
                BazProgress.buildProgressBar($('#installer-progress'));
            <?php } ?>
            BazTunnels.initPusherTunnel({'tunnelsToInit' : ['progress']});

            $('#databasetype').change(function() {
                if ($('#databasetype').find(':selected').val() === 'ff') {
                    $('#mysql').attr('hidden', true);
                } else {
                    $('#mysql').attr('hidden', false);
                }
            });

            $('#create, #create-grant').click(function() {
                if ($('#create')[0].checked === true || $('#create-grant')[0].checked === true) {
                    $('#create-username, #create-password').attr('disabled', false);
                } else if ($('#create')[0].checked === false && $('#create-grant')[0].checked === false) {
                    $('#create-username, #create-password').attr('disabled', true);
                }
            });

            $('#submit, #update').click(function(e) {
                e.preventDefault();

                var onlyFf = false;

                if ($('#databasetype').find(':selected').val() === 'ff') {
                    onlyFf = true;
                }

                if ($('#host').val() === '' && !onlyFf) {
                    $('#host').addClass('is-invalid');
                    $('#host').focus(function() {
                        $(this).removeClass('is-invalid');
                    });
                } else if ($('#port').val() === '' && !onlyFf) {
                    $('#port').addClass('is-invalid');
                    $('#port').focus(function() {
                        $(this).removeClass('is-invalid');
                    });
                } else if ($('#dbname').val() === '' && !onlyFf) {
                    $('#dbname').addClass('is-invalid');
                    $('#dbname').focus(function() {
                        $(this).removeClass('is-invalid');
                    });
                } else if ($('#charset').val() === '' && !onlyFf) {
                    $('#charset').addClass('is-invalid');
                    $('#charset').focus(function() {
                        $(this).removeClass('is-invalid');
                    });
                } else if ($('#collation').val() === '' && !onlyFf) {
                    $('#collation').addClass('is-invalid');
                    $('#collation').focus(function() {
                        $(this).removeClass('is-invalid');
                    });
                } else if ($('#username').val() === '' && !onlyFf) {
                    $('#username').addClass('is-invalid');
                    $('#username').focus(function() {
                        $(this).removeClass('is-invalid');
                    });
                } else if ($('#password').val() === '' && !onlyFf) {
                    $('#password').addClass('is-invalid');
                    $('#password').focus(function() {
                        $(this).removeClass('is-invalid');
                    });
                } else if (($('#create').length > 0 && $('#create-grant').length > 0) &&
                           ($('#create')[0].checked === true || $('#create-grant')[0].checked === true) &&
                           $('#create-username').val() === '' && !onlyFf) {
                    $('#create-username').addClass('is-invalid');
                    $('#create-username').focus(function() {
                        $(this).removeClass('is-invalid');
                    });
                } else if (($('#create').length > 0 && $('#create-grant').length > 0) &&
                           ($('#create')[0].checked === true || $('#create-grant')[0].checked === true) &&
                           $('#create-password').val() === '' && !onlyFf) {
                    $('#create-password').addClass('is-invalid');
                    $('#create-password').focus(function() {
                        $(this).removeClass('is-invalid');
                    });
                } else if ($('#email').val() === '') {
                    $('#email').addClass('is-invalid');
                    $('#email').focus(function() {
                        $(this).removeClass('is-invalid');
                    });
                } else if ($('#pass').val() === '') {
                    $('#pass').addClass('is-invalid');
                    $('#pass').focus(function() {
                        $(this).removeClass('is-invalid');
                    });
                } else if ($('#pwf').val() === '') {
                    $('#pwf').addClass('is-invalid');
                    $('#pwf').focus(function() {
                        $(this).removeClass('is-invalid');
                    });
                } else if ($('#cwf').val() === '') {
                    $('#cwf').addClass('is-invalid');
                    $('#cwf').focus(function() {
                        $(this).removeClass('is-invalid');
                    });
                } else {
                    $(this).attr('disabled', true);
                    $('#submit-spinner, #update-spinner').attr('hidden', false);
                    $('#alert').attr('hidden', true);
                    $('.installer-progress-bar').removeClass(function (index, className) {
                        return (className.match (/(^|\s)bg-\S+/g) || []).join(' ');
                    }).addClass('bg-info');

                    var data = { };
                    if ($('#databasetype').find(':selected').val() !== 'ff') {
                        data = $.extend(data,
                            {
                                "host"                  : $('#host').val(),
                                "port"                  : $('#port').val(),
                                "dbname"                : $('#dbname').val(),
                                "charset"               : $('#charset').val(),
                                "collation"             : $('#collation').val(),
                                "username"              : $('#username').val(),
                                "password"              : $('#password').val(),
                                "drop"                  : $('#drop')[0].checked,
                            });
                        if ($('#create').length > 0 && $('#create')[0].checked === true) {
                            data = $.extend(data,
                            {
                                "create-username"       : $('#create-username').val(),
                                "create-password"       : $('#create-password').val(),
                                "create-db"             : $('#create')[0].checked,
                                "create-user"           : $('#create-grant')[0].checked
                            });
                        }
                    }
                <?php if (!$onlyUpdateDb && !$precheckFail) { ?>
                    data = $.extend(data,
                        {
                            "email"                 : $('#email').val(),
                            "pass"                  : $('#pass').val(),
                            "pwf"                   : $('#pwf').val(),
                            "cwf"                   : $('#cwf').val(),
                            "auto-encrypt-level"    : $('#auto-encrypt-level')[0].checked,
                            "dev"                   : $('#dev')[0].checked,
                            "databasetype"          : $('#databasetype').val(),
                            "country"               : $('#country').val(),
                            "ip2location"           : $('#ip2location')[0].checked
                        });
                <?php } ?>
                    $('.installer-progress-bar').css('width', '0%');
                    $('.installer-progress-bar').attr('aria-valuenow', 0);
                    $('.progress-bar').addClass('progress-bar-animated');
                    $('#external-data').val('Downloading & installing external packages...');
                    $.ajax({
                        type    : 'POST',
                        url     : '/',
                        data    : data,
                        dataType: 'json',
                        success: function (data) {
                            if (data && data.responseCode === 0) {
                                var alert = 'alert-success';

                                $('#alert').attr('hidden', false);
                                $('#alert').html('');
                                if ($('#access').is('.btn-warning')) {
                                    alert = 'alert-warning';
                                }
                                $('#alert').removeClass(function (index, className) {
                                    return (className.match (/(^|\s)alert-\S+/g) || []).join(' ');
                                }).addClass(alert).html(data.responseMessage);
                                $('#access').attr('disabled', false);
                                <?php if ($onlyUpdateDb) { ?>
                                    $('#access-div').attr('hidden', false);
                                    $('#access').addClass('btn-success');
                                    $('#access').children('i').addClass('fa-check');
                                <?php } ?>
                                $('#update-div').attr('hidden', true);
                                $('#submit-spinner, #update-spinner').attr('hidden', true);
                            } else if (data.responseCode === 1 || data.responseCode === 2 || data.responseCode === 3) {
                                $('#alert').attr('hidden', false);
                                $('#alert').html('');
                                $('#alert').removeClass(function (index, className) {
                                    return (className.match (/(^|\s)alert-\S+/g) || []).join(' ');
                                }).addClass('alert-danger').html(data.responseMessage);
                                $('#submit, #update').attr('disabled', false);
                                $('#submit-spinner, #update-spinner').attr('hidden', true);

                                if (data.responseCode === 3) {
                                    BazProgress.getProgress({
                                        'url' : '/',
                                        'postData' : {
                                            'session' : $('#session-token').val(),
                                            'composer' : 'true'
                                        }
                                    }, true);
                                }
                            }
                        },
                        error: function (data) {
                            if (data.responseJSON && data.responseJSON.responseCode === 1) {
                                $('#alert').attr('hidden', false);
                                $('#alert').html('');
                                $('#alert').removeClass(function (index, className) {
                                    return (className.match (/(^|\s)alert-\S+/g) || []).join(' ');
                                }).addClass('alert-danger').html(data.responseJSON.responseMessage);
                            }
                            $('#submit, #update').attr('disabled', false);
                            $('#submit-spinner, #update-spinner').attr('hidden', true);
                            $('#external-div').attr('hidden', true);
                            $('#external-data').val('Downloading & installing external packages...');
                        }
                    });
                <?php if (!$onlyUpdateDb) { ?>
                    if (BazProgress.isOnline() === false) {
                        setTimeout(function() {
                            BazProgress.getProgress({
                                'url' : '/',
                                'postData' : {
                                    'session' : $('#session-token').val()
                                }
                            });
                        }, 1000);
                    } else {
                        BazProgress.getProgress({
                            'url' : '/',
                            'postData' : {
                                'session' : $('#session-token').val()
                            }
                        });
                    }
                <?php } ?>
                }
            });

            BazProgress.setCallable({
                beforeProcess : function(response) {
                    if (response.responseCode !== 0) {
                        return;
                    }

                    var responseData;

                    if (typeof response.responseData === 'string' || response.responseData instanceof String) {
                        responseData = JSON.parse(response.responseData);
                    } else {
                        responseData = response.responseData;
                    }

                    if (responseData['runners'] &&
                        responseData['runners']['running'] &&
                        responseData['runners']['running']['method'] === 'executeComposer'
                    ) {
                        $('#installer-progress').attr('hidden', true);
                        $('#external-div').attr('hidden', false);
                    }
                    if (responseData.composer) {
                        $('#external-data').val(responseData.composer);
                        $('#external-data').scrollTop($('#external-data')[0].scrollHeight);
                    }

                    return true;
                },
                afterProcess : function(response) {
                    if (response.responseCode !== 0) {
                        if (response.responseData.composer_error && response.responseData.composer_error == true) {
                            $('#external-data').val(response.responseData.composer);
                            $('#external-data').scrollTop($('#external-data')[0].scrollHeight);
                            $('#external-div').attr('hidden', false);
                        }

                        return;
                    }

                    var responseData, timerId;

                    if (typeof response.responseData === 'string' || response.responseData instanceof String) {
                        responseData = JSON.parse(response.responseData);
                    } else {
                        responseData = response.responseData;
                    }

                    if (responseData['runners'] &&
                        responseData['runners']['running'] &&
                        responseData['runners']['running']['method'] === 'executeComposer'
                    ) {
                        if (BazHelpers.getTimerId('composer') === false) {
                            if (BazHelpers.getTimerId('getProgress') !== false) {
                                BazHelpers.setTimeoutTimers.stop(BazHelpers.getTimerId('getProgress'), null, 'getProgress');
                            }

                            BazProgress.getProgress({
                                'url' : '/',
                                'postData' : {
                                    'session' : $('#session-token').val(),
                                    'composer' : 'true'
                                }
                            }, true);

                            BazHelpers.setTimeoutTimers.add(function() {
                                BazProgress.getProgress({
                                    'url' : '/',
                                    'postData' : {
                                        'session' : $('#session-token').val(),
                                        'composer' : 'true'
                                    }
                                }, true);
                            }, 300, null, 'composer');
                        }
                    } else {
                        timerId = BazHelpers.getTimerId('composer');
                        if (timerId) {
                            BazHelpers.setTimeoutTimers.add(function(timerId) {
                                BazHelpers.setTimeoutTimers.stop(timerId, null, 'composer');
                            });
                        }
                    }
                    return true;
                },
                onComplete : function(response) {
                    BazHelpers.setTimeoutTimers.stopAll();
                    if (response.responseCode == 0) {
                        setTimeout(function() {
                            $('#access').addClass('btn-success');
                            $('#access').children('i').addClass('fa-check');
                            $('#access-div').attr('hidden', false);
                            $('#submit-div').attr('hidden', true);
                        }, 1000);
                    }
                }
            });

            $('#auto-encrypt-level').click(function() {
                if ($(this)[0].checked === true) {
                    $('#pwf, #cwf').attr('disabled', true);
                    $('#dev')[0].checked = false;
                } else if ($(this)[0].checked === false) {
                    $('#pwf, #cwf').attr('disabled', false);
                }
            });

            $('#dev').click(function() {
                if ($(this)[0].checked === true) {
                    $('#auto-encrypt-level')[0].checked = false;
                    $('#pwf').val('2');
                    $('#cwf').val('2');
                }
            });

            $('#db_password_strength_meter').strengthMeter({
                "url"       : '/',
                "postData"  : {
                    "session"           : $('#session-token').val(),
                    "checkPwStrength"   : true
                }
            });

            $('#user_password_strength_meter').strengthMeter({
                "url"       : '/',
                "session"   : $('#session-token').val(),
                "postData"  : {
                    "session"           : $('#session-token').val(),
                    "checkPwStrength"   : true
                }
            });

            $('#password-visibility, #create-password-visibility, #pass-visibility').click(function(e) {
                e.preventDefault();

                if ($(this).parent().siblings('input').attr('type') === 'password') {
                    $(this).parent().siblings('input').attr('type', 'text');
                    $(this).children('i').removeClass('fa-eye-slash').addClass('fa-eye');
                } else if ($(this).parent().siblings('input').attr('type') === 'text') {
                    $(this).parent().siblings('input').attr('type', 'password');
                    $(this).children('i').removeClass('fa-eye').addClass('fa-eye-slash');
                }
            });

            $('#generate_db_password_button, #generate_user_password_button').click(function(e) {
                e.preventDefault();

                var that = this;
                var generatePwData = { };
                generatePwData['session'] = $('#session-token').val();
                generatePwData['generatePw'] = true;

                $.post('/', generatePwData, function(response) {
                    if (response.responseCode == 0) {
                        if (response.responseData) {
                            if ($(that)[0].id === 'generate_db_password_button') {
                                $('#password').val(response.responseData).trigger('change');
                                $('#password').attr('type', 'text');
                                $('#password-visibility').children('i').removeClass('fa-eye-slash').addClass('fa-eye');
                            } else if ($(that)[0].id === 'generate_user_password_button') {
                                $('#pass').val(response.responseData).trigger('change');
                                $('#pass').attr('type', 'text');
                                $('#pass-visibility').children('i').removeClass('fa-eye-slash').addClass('fa-eye');
                            }
                        }
                    } else {
                        PNotify.error(response.responseMessage);
                    }
                }, 'json');
            });
        </script>
    </body>
</html>