<?php

namespace Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types;

use Apps\Dash\Packages\System\Api\Base\Types\BaseType;

class ItemType extends BaseType
{
    private static $propertyTypes = [
        'ApplicationData' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ApplicationData',
        ],
        'AttributeSetArray' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AttributeSetArrayType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'AttributeSetArray',
        ],
        'AttributeArray' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AttributeArrayType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'AttributeArray',
        ],
        'LookupAttributeArray' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\LookupAttributeArrayType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LookupAttributeArray',
        ],
        'AutoPay' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'AutoPay',
        ],
        'BiddingDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\BiddingDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BiddingDetails',
        ],
        'BuyerProtection' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\BuyerProtectionCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BuyerProtection',
        ],
        'BuyItNowPrice' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AmountType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BuyItNowPrice',
        ],
        'CategoryMappingAllowed' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'CategoryMappingAllowed',
        ],
        'Charity' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\CharityType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Charity',
        ],
        'Country' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\CountryCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Country',
        ],
        'CrossPromotion' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\CrossPromotionsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'CrossPromotion',
        ],
        'Currency' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\CurrencyCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Currency',
        ],
        'Description' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Description',
        ],
        'DescriptionReviseMode' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\DescriptionReviseModeCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DescriptionReviseMode',
        ],
        'Distance' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\DistanceType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Distance',
        ],
        'HitCounter' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\HitCounterCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'HitCounter',
        ],
        'ItemID' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ItemID',
        ],
        'ListingDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ListingDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ListingDetails',
        ],
        'ListingDuration' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ListingDuration',
        ],
        'ListingEnhancement' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ListingEnhancementsCodeType',
          'repeatable' => true,
          'attribute' => false,
          'elementName' => 'ListingEnhancement',
        ],
        'ListingType' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ListingTypeCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ListingType',
        ],
        'Location' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Location',
        ],
        'LotSize' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LotSize',
        ],
        'PartnerCode' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PartnerCode',
        ],
        'PartnerName' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PartnerName',
        ],
        'PaymentDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\PaymentDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PaymentDetails',
        ],
        'PaymentMethods' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\BuyerPaymentMethodCodeType',
          'repeatable' => true,
          'attribute' => false,
          'elementName' => 'PaymentMethods',
        ],
        'PayPalEmailAddress' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PayPalEmailAddress',
        ],
        'PrimaryCategory' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\CategoryType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PrimaryCategory',
        ],
        'PrivateListing' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PrivateListing',
        ],
        'ProductListingDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ProductListingDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ProductListingDetails',
        ],
        'Quantity' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Quantity',
        ],
        'PrivateNotes' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PrivateNotes',
        ],
        'RegionID' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'RegionID',
        ],
        'RelistLink' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'RelistLink',
        ],
        'ReservePrice' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AmountType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ReservePrice',
        ],
        'ReviseStatus' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ReviseStatusType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ReviseStatus',
        ],
        'ScheduleTime' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ScheduleTime',
        ],
        'SecondaryCategory' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\CategoryType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SecondaryCategory',
        ],
        'FreeAddedCategory' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\CategoryType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'FreeAddedCategory',
        ],
        'Seller' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\UserType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Seller',
        ],
        'SellingStatus' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\SellingStatusType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SellingStatus',
        ],
        'ShippingDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ShippingDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ShippingDetails',
        ],
        'ShipToLocations' => [
          'type' =>       'string',
          'repeatable' => true,
          'attribute' => false,
          'elementName' => 'ShipToLocations',
        ],
        'Site' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\SiteCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Site',
        ],
        'StartPrice' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AmountType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'StartPrice',
        ],
        'Storefront' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\StorefrontType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Storefront',
        ],
        'SubTitle' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SubTitle',
        ],
        'TimeLeft' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'TimeLeft',
        ],
        'Title' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Title',
        ],
        'UUID' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'UUID',
        ],
        'VATDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\VATDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'VATDetails',
        ],
        'SellerVacationNote' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SellerVacationNote',
        ],
        'WatchCount' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'WatchCount',
        ],
        'HitCount' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'HitCount',
        ],
        'DisableBuyerRequirements' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DisableBuyerRequirements',
        ],
        'BestOfferDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\BestOfferDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BestOfferDetails',
        ],
        'LocationDefaulted' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocationDefaulted',
        ],
        'UseTaxTable' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'UseTaxTable',
        ],
        'GetItFast' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'GetItFast',
        ],
        'BuyerResponsibleForShipping' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BuyerResponsibleForShipping',
        ],
        'LimitedWarrantyEligible' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LimitedWarrantyEligible',
        ],
        'eBayNotes' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayNotes',
        ],
        'QuestionCount' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'QuestionCount',
        ],
        'Relisted' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Relisted',
        ],
        'QuantityAvailable' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'QuantityAvailable',
        ],
        'SKU' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SKU',
        ],
        'SearchDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\SearchDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SearchDetails',
        ],
        'PostalCode' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PostalCode',
        ],
        'PictureDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\PictureDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PictureDetails',
        ],
        'DispatchTimeMax' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DispatchTimeMax',
        ],
        'BestOfferEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BestOfferEnabled',
        ],
        'LocalListing' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalListing',
        ],
        'SellerContactDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AddressType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SellerContactDetails',
        ],
        'TotalQuestionCount' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'TotalQuestionCount',
        ],
        'ProxyItem' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ProxyItem',
        ],
        'ExtendedSellerContactDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ExtendedContactDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ExtendedSellerContactDetails',
        ],
        'LeadCount' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LeadCount',
        ],
        'NewLeadCount' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'NewLeadCount',
        ],
        'ItemSpecifics' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\NameValueListArrayType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ItemSpecifics',
        ],
        'GroupCategoryID' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'GroupCategoryID',
        ],
        'ClassifiedAdPayPerLeadFee' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AmountType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdPayPerLeadFee',
        ],
        'BidGroupItem' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BidGroupItem',
        ],
        'ApplyBuyerProtection' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\BuyerProtectionDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ApplyBuyerProtection',
        ],
        'ListingSubtype2' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ListingSubtypeCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ListingSubtype2',
        ],
        'MechanicalCheckAccepted' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'MechanicalCheckAccepted',
        ],
        'UpdateSellerInfo' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'UpdateSellerInfo',
        ],
        'UpdateReturnPolicy' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'UpdateReturnPolicy',
        ],
        'ItemPolicyViolation' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ItemPolicyViolationType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ItemPolicyViolation',
        ],
        'CrossBorderTrade' => [
          'type' =>       'string',
          'repeatable' => true,
          'attribute' => false,
          'elementName' => 'CrossBorderTrade',
        ],
        'BusinessSellerDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\BusinessSellerDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BusinessSellerDetails',
        ],
        'BuyerGuaranteePrice' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AmountType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BuyerGuaranteePrice',
        ],
        'BuyerRequirementDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\BuyerRequirementDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BuyerRequirementDetails',
        ],
        'ReturnPolicy' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ReturnPolicyType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ReturnPolicy',
        ],
        'PaymentAllowedSite' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\SiteCodeType',
          'repeatable' => true,
          'attribute' => false,
          'elementName' => 'PaymentAllowedSite',
        ],
        'InventoryTrackingMethod' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\InventoryTrackingMethodCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'InventoryTrackingMethod',
        ],
        'IntegratedMerchantCreditCardEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'IntegratedMerchantCreditCardEnabled',
        ],
        'Variations' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\VariationsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Variations',
        ],
        'ItemCompatibilityList' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ItemCompatibilityListType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ItemCompatibilityList',
        ],
        'ItemCompatibilityCount' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ItemCompatibilityCount',
        ],
        'ConditionID' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ConditionID',
        ],
        'ConditionDescription' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ConditionDescription',
        ],
        'ConditionDisplayName' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ConditionDisplayName',
        ],
        'TaxCategory' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'TaxCategory',
        ],
        'QuantityAvailableHint' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\QuantityAvailableHintCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'QuantityAvailableHint',
        ],
        'QuantityThreshold' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'QuantityThreshold',
        ],
        'DiscountPriceInfo' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\DiscountPriceInfoType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DiscountPriceInfo',
        ],
        'SellerProvidedTitle' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SellerProvidedTitle',
        ],
        'VIN' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'VIN',
        ],
        'VINLink' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'VINLink',
        ],
        'VRM' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'VRM',
        ],
        'VRMLink' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'VRMLink',
        ],
        'QuantityInfo' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\QuantityInfoType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'QuantityInfo',
        ],
        'SellerProfiles' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\SellerProfilesType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SellerProfiles',
        ],
        'ShippingServiceCostOverrideList' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ShippingServiceCostOverrideListType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ShippingServiceCostOverrideList',
        ],
        'ShippingOverride' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ShippingOverrideType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ShippingOverride',
        ],
        'ShippingPackageDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ShipPackageDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ShippingPackageDetails',
        ],
        'TopRatedListing' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'TopRatedListing',
        ],
        'QuantityRestrictionPerBuyer' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\QuantityRestrictionPerBuyerInfoType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'QuantityRestrictionPerBuyer',
        ],
        'FloorPrice' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AmountType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'FloorPrice',
        ],
        'CeilingPrice' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AmountType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'CeilingPrice',
        ],
        'IsIntermediatedShippingEligible' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'IsIntermediatedShippingEligible',
        ],
        'UnitInfo' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\UnitInfoType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'UnitInfo',
        ],
        'RelistParentID' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'RelistParentID',
        ],
        'ConditionDefinition' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ConditionDefinition',
        ],
        'HideFromSearch' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'HideFromSearch',
        ],
        'ReasonHideFromSearch' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ReasonHideFromSearchCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ReasonHideFromSearch',
        ],
        'IncludeRecommendations' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'IncludeRecommendations',
        ],
        'PickupInStoreDetails' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\PickupInStoreDetailsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PickupInStoreDetails',
        ],
        'SiteId' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SiteId',
        ],
        'IgnoreQuantity' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'IgnoreQuantity',
        ],
        'AvailableForPickupDropOff' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'AvailableForPickupDropOff',
        ],
        'EligibleForPickupDropOff' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'EligibleForPickupDropOff',
        ],
        'LiveAuction' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LiveAuction',
        ],
        'DigitalGoodInfo' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\DigitalGoodInfoType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DigitalGoodInfo',
        ],
        'eBayPlus' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayPlus',
        ],
        'eBayPlusEligible' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayPlusEligible',
        ],
        'eMailDeliveryAvailable' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eMailDeliveryAvailable',
        ],
        'IsSecureDescription' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'IsSecureDescription',
        ],
      ];

    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}