<?php

namespace Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types;

use Apps\Dash\Packages\System\Api\Base\Types\BaseType;

class SiteDefaultsType extends BaseType
{
    private static $propertyTypes = [
        'ListingDuration' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ListingDurationReferenceType',
          'repeatable' => true,
          'attribute' => false,
          'elementName' => 'ListingDuration',
        ],
        'ShippingTermsRequired' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ShippingTermsRequired',
        ],
        'BestOfferEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BestOfferEnabled',
        ],
        'DutchBINEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DutchBINEnabled',
        ],
        'UserConsentRequired' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'UserConsentRequired',
        ],
        'HomePageFeaturedEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'HomePageFeaturedEnabled',
        ],
        'ProPackEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ProPackEnabled',
        ],
        'BasicUpgradePackEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BasicUpgradePackEnabled',
        ],
        'ValuePackEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ValuePackEnabled',
        ],
        'ProPackPlusEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ProPackPlusEnabled',
        ],
        'AdFormatEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AdFormatEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'AdFormatEnabled',
        ],
        'BestOfferCounterEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BestOfferCounterEnabled',
        ],
        'BestOfferAutoDeclineEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BestOfferAutoDeclineEnabled',
        ],
        'LocalMarketSpecialitySubscription' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketSpecialitySubscription',
        ],
        'LocalMarketRegularSubscription' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketRegularSubscription',
        ],
        'LocalMarketPremiumSubscription' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketPremiumSubscription',
        ],
        'LocalMarketNonSubscription' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketNonSubscription',
        ],
        'ExpressEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ExpressEnabled',
        ],
        'ExpressPicturesRequired' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ExpressPicturesRequired',
        ],
        'ExpressConditionRequired' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ExpressConditionRequired',
        ],
        'MinimumReservePrice' => [
          'type' => 'number',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'MinimumReservePrice',
        ],
        'SellerContactDetailsEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SellerContactDetailsEnabled',
        ],
        'TransactionConfirmationRequestEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'TransactionConfirmationRequestEnabled',
        ],
        'StoreInventoryEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'StoreInventoryEnabled',
        ],
        'SkypeMeTransactionalEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SkypeMeTransactionalEnabled',
        ],
        'SkypeMeNonTransactionalEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SkypeMeNonTransactionalEnabled',
        ],
        'LocalListingDistancesRegular' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalListingDistancesRegular',
        ],
        'LocalListingDistancesSpecialty' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalListingDistancesSpecialty',
        ],
        'LocalListingDistancesNonSubscription' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalListingDistancesNonSubscription',
        ],
        'ClassifiedAdPaymentMethodEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ClassifiedAdPaymentMethodEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdPaymentMethodEnabled',
        ],
        'ClassifiedAdShippingMethodEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdShippingMethodEnabled',
        ],
        'ClassifiedAdBestOfferEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ClassifiedAdBestOfferEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdBestOfferEnabled',
        ],
        'ClassifiedAdCounterOfferEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdCounterOfferEnabled',
        ],
        'ClassifiedAdAutoDeclineEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdAutoDeclineEnabled',
        ],
        'ClassifiedAdContactByPhoneEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdContactByPhoneEnabled',
        ],
        'ClassifiedAdContactByEmailEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdContactByEmailEnabled',
        ],
        'SafePaymentRequired' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SafePaymentRequired',
        ],
        'ClassifiedAdPayPerLeadEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdPayPerLeadEnabled',
        ],
        'ItemSpecificsEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ItemSpecificsEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ItemSpecificsEnabled',
        ],
        'PaisaPayFullEscrowEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PaisaPayFullEscrowEnabled',
        ],
        'ISBNIdentifierEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ISBNIdentifierEnabled',
        ],
        'UPCIdentifierEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'UPCIdentifierEnabled',
        ],
        'EANIdentifierEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'EANIdentifierEnabled',
        ],
        'BrandMPNIdentifierEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BrandMPNIdentifierEnabled',
        ],
        'ClassifiedAdAutoAcceptEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdAutoAcceptEnabled',
        ],
        'BestOfferAutoAcceptEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BestOfferAutoAcceptEnabled',
        ],
        'CrossBorderTradeNorthAmericaEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'CrossBorderTradeNorthAmericaEnabled',
        ],
        'CrossBorderTradeGBEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'CrossBorderTradeGBEnabled',
        ],
        'CrossBorderTradeAustraliaEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'CrossBorderTradeAustraliaEnabled',
        ],
        'PayPalBuyerProtectionEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PayPalBuyerProtectionEnabled',
        ],
        'BuyerGuaranteeEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BuyerGuaranteeEnabled',
        ],
        'INEscrowWorkflowTimeline' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\INEscrowWorkflowTimelineCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'INEscrowWorkflowTimeline',
        ],
        'CombinedFixedPriceTreatmentEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'CombinedFixedPriceTreatmentEnabled',
        ],
        'GalleryFeaturedDurations' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ListingEnhancementDurationReferenceType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'GalleryFeaturedDurations',
        ],
        'PayPalRequired' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PayPalRequired',
        ],
        'eBayMotorsProAdFormatEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AdFormatEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProAdFormatEnabled',
        ],
        'eBayMotorsProContactByPhoneEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProContactByPhoneEnabled',
        ],
        'eBayMotorsProPhoneCount' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProPhoneCount',
        ],
        'eBayMotorsProContactByAddressEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProContactByAddressEnabled',
        ],
        'eBayMotorsProStreetCount' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProStreetCount',
        ],
        'eBayMotorsProCompanyNameEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProCompanyNameEnabled',
        ],
        'eBayMotorsProContactByEmailEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProContactByEmailEnabled',
        ],
        'eBayMotorsProBestOfferEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ClassifiedAdBestOfferEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProBestOfferEnabled',
        ],
        'eBayMotorsProAutoAcceptEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProAutoAcceptEnabled',
        ],
        'eBayMotorsProAutoDeclineEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProAutoDeclineEnabled',
        ],
        'eBayMotorsProPaymentMethodCheckOutEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ClassifiedAdPaymentMethodEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProPaymentMethodCheckOutEnabled',
        ],
        'eBayMotorsProShippingMethodEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProShippingMethodEnabled',
        ],
        'eBayMotorsProCounterOfferEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProCounterOfferEnabled',
        ],
        'eBayMotorsProSellerContactDetailsEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProSellerContactDetailsEnabled',
        ],
        'LocalMarketAdFormatEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AdFormatEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketAdFormatEnabled',
        ],
        'LocalMarketContactByPhoneEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketContactByPhoneEnabled',
        ],
        'LocalMarketPhoneCount' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketPhoneCount',
        ],
        'LocalMarketContactByAddressEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketContactByAddressEnabled',
        ],
        'LocalMarketStreetCount' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketStreetCount',
        ],
        'LocalMarketCompanyNameEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketCompanyNameEnabled',
        ],
        'LocalMarketContactByEmailEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketContactByEmailEnabled',
        ],
        'LocalMarketBestOfferEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ClassifiedAdBestOfferEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketBestOfferEnabled',
        ],
        'LocalMarketAutoAcceptEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketAutoAcceptEnabled',
        ],
        'LocalMarketAutoDeclineEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketAutoDeclineEnabled',
        ],
        'LocalMarketPaymentMethodCheckOutEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ClassifiedAdPaymentMethodEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketPaymentMethodCheckOutEnabled',
        ],
        'LocalMarketShippingMethodEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketShippingMethodEnabled',
        ],
        'LocalMarketCounterOfferEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketCounterOfferEnabled',
        ],
        'LocalMarketSellerContactDetailsEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketSellerContactDetailsEnabled',
        ],
        'ClassifiedAdPhoneCount' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdPhoneCount',
        ],
        'ClassifiedAdContactByAddressEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdContactByAddressEnabled',
        ],
        'ClassifiedAdStreetCount' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdStreetCount',
        ],
        'ClassifiedAdCompanyNameEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdCompanyNameEnabled',
        ],
        'SpecialitySubscription' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\GeographicExposureCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SpecialitySubscription',
        ],
        'RegularSubscription' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\GeographicExposureCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'RegularSubscription',
        ],
        'PremiumSubscription' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\GeographicExposureCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PremiumSubscription',
        ],
        'NonSubscription' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\GeographicExposureCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'NonSubscription',
        ],
        'PayPalRequiredForStoreOwner' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PayPalRequiredForStoreOwner',
        ],
        'ReviseQuantityAllowed' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ReviseQuantityAllowed',
        ],
        'RevisePriceAllowed' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'RevisePriceAllowed',
        ],
        'StoreOwnerExtendedListingDurationsEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'StoreOwnerExtendedListingDurationsEnabled',
        ],
        'StoreOwnerExtendedListingDurations' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\StoreOwnerExtendedListingDurationsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'StoreOwnerExtendedListingDurations',
        ],
        'ReturnPolicyEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ReturnPolicyEnabled',
        ],
        'HandlingTimeEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'HandlingTimeEnabled',
        ],
        'MaxFlatShippingCost' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AmountType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'MaxFlatShippingCost',
        ],
        'MaxFlatShippingCostCBTExempt' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'MaxFlatShippingCostCBTExempt',
        ],
        'Group1MaxFlatShippingCost' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AmountType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Group1MaxFlatShippingCost',
        ],
        'Group2MaxFlatShippingCost' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AmountType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Group2MaxFlatShippingCost',
        ],
        'Group3MaxFlatShippingCost' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AmountType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Group3MaxFlatShippingCost',
        ],
        'PaymentMethod' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\BuyerPaymentMethodCodeType',
          'repeatable' => true,
          'attribute' => false,
          'elementName' => 'PaymentMethod',
        ],
        'VariationsEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'VariationsEnabled',
        ],
        'AttributeConversionEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\AttributeConversionEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'AttributeConversionEnabled',
        ],
        'FreeGalleryPlusEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'FreeGalleryPlusEnabled',
        ],
        'FreePicturePackEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'FreePicturePackEnabled',
        ],
        'ItemCompatibilityEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ItemCompatibilityEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ItemCompatibilityEnabled',
        ],
        'MinItemCompatibility' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'MinItemCompatibility',
        ],
        'MaxItemCompatibility' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'MaxItemCompatibility',
        ],
        'ConditionEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ConditionEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ConditionEnabled',
        ],
        'ConditionValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ConditionValuesType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ConditionValues',
        ],
        'ValueCategory' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ValueCategory',
        ],
        'ProductCreationEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ProductCreationEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ProductCreationEnabled',
        ],
        'EANEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ProductIdentiferEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'EANEnabled',
        ],
        'ISBNEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ProductIdentiferEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ISBNEnabled',
        ],
        'UPCEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ProductIdentiferEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'UPCEnabled',
        ],
        'MaxGranularFitmentCount' => [
          'type' => 'integer',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'MaxGranularFitmentCount',
        ],
        'CompatibleVehicleType' => [
          'type' =>       'string',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'CompatibleVehicleType',
        ],
        'PaymentOptionsGroup' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\PaymentOptionsGroupEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PaymentOptionsGroup',
        ],
        'ShippingProfileCategoryGroup' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ProfileCategoryGroupCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ShippingProfileCategoryGroup',
        ],
        'PaymentProfileCategoryGroup' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ProfileCategoryGroupCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PaymentProfileCategoryGroup',
        ],
        'ReturnPolicyProfileCategoryGroup' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ProfileCategoryGroupCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ReturnPolicyProfileCategoryGroup',
        ],
        'VINSupported' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'VINSupported',
        ],
        'VRMSupported' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'VRMSupported',
        ],
        'SellerProvidedTitleSupported' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SellerProvidedTitleSupported',
        ],
        'DepositSupported' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DepositSupported',
        ],
        'GlobalShippingEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'GlobalShippingEnabled',
        ],
        'AdditionalCompatibilityEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'AdditionalCompatibilityEnabled',
        ],
        'PickupDropOffEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PickupDropOffEnabled',
        ],
        'DigitalGoodDeliveryEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DigitalGoodDeliveryEnabled',
        ],
        'EpidSupported' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'EpidSupported',
        ],
        'KTypeSupported' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'KTypeSupported',
        ],
        'ProductRequiredEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\ProductRequiredEnabledCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ProductRequiredEnabled',
        ],
        'DomesticReturnsAcceptedValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\DomesticReturnsAcceptedCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DomesticReturnsAcceptedValues',
        ],
        'InternationalReturnsAcceptedValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\InternationalReturnsAcceptedCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'InternationalReturnsAcceptedValues',
        ],
        'DomesticReturnsDurationValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\DomesticReturnsDurationCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DomesticReturnsDurationValues',
        ],
        'InternationalReturnsDurationValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\InternationalReturnsDurationCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'InternationalReturnsDurationValues',
        ],
        'DomesticReturnsShipmentPayeeValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\DomesticReturnsShipmentPayeeCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DomesticReturnsShipmentPayeeValues',
        ],
        'InternationalReturnsShipmentPayeeValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\InternationalReturnsShipmentPayeeCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'InternationalReturnsShipmentPayeeValues',
        ],
        'DomesticRefundMethodValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\DomesticRefundMethodCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DomesticRefundMethodValues',
        ],
        'InternationalRefundMethodValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\EbayTradingApi\Types\InternationalRefundMethodCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'InternationalRefundMethodValues',
        ],
        'ReturnPolicyDescriptionEnabled' => [
          'type' => 'boolean',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ReturnPolicyDescriptionEnabled',
        ],
      ];

    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}