<?php

return
	[
		'System\Base\Providers\ConfigServiceProvider',
		'System\Base\Providers\SessionServiceProvider',
		'System\Base\Providers\DatabaseServiceProvider',
		'System\Base\Providers\CacheServiceProvider',
		'System\Base\Providers\ModulesServiceProvider',
		'System\Base\Providers\HttpServiceProvider',
		'System\Base\Providers\EmailServiceProvider',
		'System\Base\Providers\LoggerServiceProvider',
		'System\Base\Providers\ContentServiceProvider',
		'System\Base\Providers\RouterServiceProvider',
		'System\Base\Providers\DispatcherServiceProvider',
		'System\Base\Providers\ViewServiceProvider',
		'System\Base\Providers\FlashServiceProvider',
		'System\Base\Providers\ErrorServiceProvider',
		'System\Base\Providers\WidgetServiceProvider',
		'System\Base\Providers\AccessServiceProvider'
	];