<?php

namespace Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types;

use Apps\Dash\Packages\System\Api\Base\Types\BaseType;

class FeatureDefinitionsType extends BaseType
{
    private static $propertyTypes = [
        'ListingDurations' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ListingDurationDefinitionsType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ListingDurations',
        ],
        'ShippingTermsRequired' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ShippingTermRequiredDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ShippingTermsRequired',
        ],
        'BestOfferEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\BestOfferEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BestOfferEnabled',
        ],
        'DutchBINEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\DutchBINEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DutchBINEnabled',
        ],
        'UserConsentRequired' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\UserConsentRequiredDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'UserConsentRequired',
        ],
        'HomePageFeaturedEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\HomePageFeaturedEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'HomePageFeaturedEnabled',
        ],
        'ProPackEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ProPackEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ProPackEnabled',
        ],
        'BasicUpgradePackEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\BasicUpgradePackEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BasicUpgradePackEnabled',
        ],
        'ValuePackEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ValuePackEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ValuePackEnabled',
        ],
        'ProPackPlusEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ProPackPlusEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ProPackPlusEnabled',
        ],
        'AdFormatEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\AdFormatEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'AdFormatEnabled',
        ],
        'BestOfferCounterEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\BestOfferCounterEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BestOfferCounterEnabled',
        ],
        'BestOfferAutoDeclineEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\BestOfferAutoDeclineEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BestOfferAutoDeclineEnabled',
        ],
        'LocalMarketSpecialitySubscription' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketSpecialitySubscriptionDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketSpecialitySubscription',
        ],
        'LocalMarketRegularSubscription' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketRegularSubscriptionDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketRegularSubscription',
        ],
        'LocalMarketPremiumSubscription' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketPremiumSubscriptionDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketPremiumSubscription',
        ],
        'LocalMarketNonSubscription' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketNonSubscriptionDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketNonSubscription',
        ],
        'ExpressEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ExpressEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ExpressEnabled',
        ],
        'ExpressPicturesRequired' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ExpressPicturesRequiredDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ExpressPicturesRequired',
        ],
        'ExpressConditionRequired' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ExpressConditionRequiredDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ExpressConditionRequired',
        ],
        'MinimumReservePrice' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\MinimumReservePriceDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'MinimumReservePrice',
        ],
        'TransactionConfirmationRequestEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\TCREnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'TransactionConfirmationRequestEnabled',
        ],
        'SellerContactDetailsEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\SellerContactDetailsEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SellerContactDetailsEnabled',
        ],
        'StoreInventoryEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\StoreInventoryEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'StoreInventoryEnabled',
        ],
        'SkypeMeTransactionalEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\SkypeMeTransactionalEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SkypeMeTransactionalEnabled',
        ],
        'SkypeMeNonTransactionalEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\SkypeMeNonTransactionalEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SkypeMeNonTransactionalEnabled',
        ],
        'LocalListingDistancesRegular' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalListingDistancesRegularDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalListingDistancesRegular',
        ],
        'LocalListingDistancesSpecialty' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalListingDistancesSpecialtyDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalListingDistancesSpecialty',
        ],
        'LocalListingDistancesNonSubscription' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalListingDistancesNonSubscriptionDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalListingDistancesNonSubscription',
        ],
        'ClassifiedAdPaymentMethodEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ClassifiedAdPaymentMethodEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdPaymentMethodEnabled',
        ],
        'ClassifiedAdShippingMethodEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ClassifiedAdShippingMethodEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdShippingMethodEnabled',
        ],
        'ClassifiedAdBestOfferEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ClassifiedAdBestOfferEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdBestOfferEnabled',
        ],
        'ClassifiedAdCounterOfferEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ClassifiedAdCounterOfferEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdCounterOfferEnabled',
        ],
        'ClassifiedAdAutoDeclineEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ClassifiedAdAutoDeclineEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdAutoDeclineEnabled',
        ],
        'ClassifiedAdContactByPhoneEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ClassifiedAdContactByPhoneEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdContactByPhoneEnabled',
        ],
        'ClassifiedAdContactByEmailEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ClassifiedAdContactByEmailEnabledDefintionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdContactByEmailEnabled',
        ],
        'SafePaymentRequired' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\SafePaymentRequiredDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SafePaymentRequired',
        ],
        'ClassifiedAdPayPerLeadEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ClassifiedAdPayPerLeadEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdPayPerLeadEnabled',
        ],
        'ItemSpecificsEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ItemSpecificsEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ItemSpecificsEnabled',
        ],
        'PaisaPayFullEscrowEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\PaisaPayFullEscrowEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PaisaPayFullEscrowEnabled',
        ],
        'ISBNIdentifierEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ISBNIdentifierEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ISBNIdentifierEnabled',
        ],
        'UPCIdentifierEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\UPCIdentifierEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'UPCIdentifierEnabled',
        ],
        'EANIdentifierEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\EANIdentifierEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'EANIdentifierEnabled',
        ],
        'BrandMPNIdentifierEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\BrandMPNIdentifierEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BrandMPNIdentifierEnabled',
        ],
        'BestOfferAutoAcceptEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\BestOfferAutoAcceptEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BestOfferAutoAcceptEnabled',
        ],
        'ClassifiedAdAutoAcceptEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ClassifiedAdAutoAcceptEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdAutoAcceptEnabled',
        ],
        'CrossBorderTradeNorthAmericaEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\CrossBorderTradeNorthAmericaEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'CrossBorderTradeNorthAmericaEnabled',
        ],
        'CrossBorderTradeGBEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\CrossBorderTradeGBEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'CrossBorderTradeGBEnabled',
        ],
        'CrossBorderTradeAustraliaEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\CrossBorderTradeAustraliaEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'CrossBorderTradeAustraliaEnabled',
        ],
        'PayPalBuyerProtectionEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\PayPalBuyerProtectionEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PayPalBuyerProtectionEnabled',
        ],
        'BuyerGuaranteeEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\BuyerGuaranteeEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'BuyerGuaranteeEnabled',
        ],
        'CombinedFixedPriceTreatmentEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\CombinedFixedPriceTreatmentEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'CombinedFixedPriceTreatmentEnabled',
        ],
        'GalleryFeaturedDurations' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ListingEnhancementDurationDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'GalleryFeaturedDurations',
        ],
        'INEscrowWorkflowTimeline' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\INEscrowWorkflowTimelineDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'INEscrowWorkflowTimeline',
        ],
        'PayPalRequired' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\PayPalRequiredDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PayPalRequired',
        ],
        'eBayMotorsProAdFormatEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\eBayMotorsProAdFormatEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProAdFormatEnabled',
        ],
        'eBayMotorsProContactByPhoneEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\eBayMotorsProContactByPhoneEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProContactByPhoneEnabled',
        ],
        'eBayMotorsProPhoneCount' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\eBayMotorsProPhoneCountDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProPhoneCount',
        ],
        'eBayMotorsProContactByAddressEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\eBayMotorsProContactByAddressEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProContactByAddressEnabled',
        ],
        'eBayMotorsProStreetCount' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\eBayMotorsProStreetCountDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProStreetCount',
        ],
        'eBayMotorsProCompanyNameEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\eBayMotorsProCompanyNameEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProCompanyNameEnabled',
        ],
        'eBayMotorsProContactByEmailEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\eBayMotorsProContactByEmailEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProContactByEmailEnabled',
        ],
        'eBayMotorsProBestOfferEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\eBayMotorsProBestOfferEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProBestOfferEnabled',
        ],
        'eBayMotorsProAutoAcceptEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\eBayMotorsProAutoAcceptEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProAutoAcceptEnabled',
        ],
        'eBayMotorsProAutoDeclineEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\eBayMotorsProAutoDeclineEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProAutoDeclineEnabled',
        ],
        'eBayMotorsProPaymentMethodCheckOutEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\eBayMotorsProPaymentMethodCheckOutEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProPaymentMethodCheckOutEnabled',
        ],
        'eBayMotorsProShippingMethodEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\eBayMotorsProShippingMethodEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProShippingMethodEnabled',
        ],
        'eBayMotorsProCounterOfferEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\eBayMotorsProCounterOfferEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProCounterOfferEnabled',
        ],
        'eBayMotorsProSellerContactDetailsEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\eBayMotorsProSellerContactDetailsEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'eBayMotorsProSellerContactDetailsEnabled',
        ],
        'LocalMarketAdFormatEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketAdFormatEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketAdFormatEnabled',
        ],
        'LocalMarketContactByPhoneEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketContactByPhoneEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketContactByPhoneEnabled',
        ],
        'LocalMarketPhoneCount' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketPhoneCountDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketPhoneCount',
        ],
        'LocalMarketContactByAddressEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketContactByAddressEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketContactByAddressEnabled',
        ],
        'LocalMarketStreetCount' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketStreetCountDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketStreetCount',
        ],
        'LocalMarketCompanyNameEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketCompanyNameEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketCompanyNameEnabled',
        ],
        'LocalMarketContactByEmailEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketContactByEmailEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketContactByEmailEnabled',
        ],
        'LocalMarketBestOfferEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketBestOfferEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketBestOfferEnabled',
        ],
        'LocalMarketAutoAcceptEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketAutoAcceptEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketAutoAcceptEnabled',
        ],
        'LocalMarketAutoDeclineEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketAutoDeclineEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketAutoDeclineEnabled',
        ],
        'LocalMarketPaymentMethodCheckOutEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketPaymentMethodCheckOutEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketPaymentMethodCheckOutEnabled',
        ],
        'LocalMarketShippingMethodEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketShippingMethodEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketShippingMethodEnabled',
        ],
        'LocalMarketCounterOfferEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketCounterOfferEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketCounterOfferEnabled',
        ],
        'LocalMarketSellerContactDetailsEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\LocalMarketSellerContactDetailsEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'LocalMarketSellerContactDetailsEnabled',
        ],
        'ClassifiedAdPhoneCount' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ClassifiedAdPhoneCountDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdPhoneCount',
        ],
        'ClassifiedAdContactByAddressEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ClassifiedAdContactByAddressEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdContactByAddressEnabled',
        ],
        'ClassifiedAdStreetCount' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ClassifiedAdStreetCountDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdStreetCount',
        ],
        'ClassifiedAdCompanyNameEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ClassifiedAdCompanyNameEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ClassifiedAdCompanyNameEnabled',
        ],
        'SpecialitySubscription' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\SpecialitySubscriptionDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SpecialitySubscription',
        ],
        'RegularSubscription' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\RegularSubscriptionDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'RegularSubscription',
        ],
        'PremiumSubscription' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\PremiumSubscriptionDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PremiumSubscription',
        ],
        'NonSubscription' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\NonSubscriptionDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'NonSubscription',
        ],
        'ReturnPolicyEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ReturnPolicyEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ReturnPolicyEnabled',
        ],
        'HandlingTimeEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\HandlingTimeEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'HandlingTimeEnabled',
        ],
        'PayPalRequiredForStoreOwner' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\PayPalRequiredForStoreOwnerDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PayPalRequiredForStoreOwner',
        ],
        'ReviseQuantityAllowed' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ReviseQuantityAllowedDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ReviseQuantityAllowed',
        ],
        'RevisePriceAllowed' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\RevisePriceAllowedDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'RevisePriceAllowed',
        ],
        'StoreOwnerExtendedListingDurationsEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\StoreOwnerExtendedListingDurationsEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'StoreOwnerExtendedListingDurationsEnabled',
        ],
        'StoreOwnerExtendedListingDurations' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\StoreOwnerExtendedListingDurationsDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'StoreOwnerExtendedListingDurations',
        ],
        'PaymentMethod' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\PaymentMethodDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PaymentMethod',
        ],
        'Group1MaxFlatShippingCost' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\Group1MaxFlatShippingCostDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Group1MaxFlatShippingCost',
        ],
        'Group2MaxFlatShippingCost' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\Group2MaxFlatShippingCostDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Group2MaxFlatShippingCost',
        ],
        'Group3MaxFlatShippingCost' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\Group3MaxFlatShippingCostDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'Group3MaxFlatShippingCost',
        ],
        'MaxFlatShippingCostCBTExempt' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\MaxFlatShippingCostCBTExemptDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'MaxFlatShippingCostCBTExempt',
        ],
        'MaxFlatShippingCost' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\MaxFlatShippingCostDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'MaxFlatShippingCost',
        ],
        'VariationsEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\VariationsEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'VariationsEnabled',
        ],
        'AttributeConversionEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\AttributeConversionEnabledFeatureDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'AttributeConversionEnabled',
        ],
        'FreeGalleryPlusEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\FreeGalleryPlusEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'FreeGalleryPlusEnabled',
        ],
        'FreePicturePackEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\FreePicturePackEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'FreePicturePackEnabled',
        ],
        'ItemCompatibilityEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ItemCompatibilityEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ItemCompatibilityEnabled',
        ],
        'MaxItemCompatibility' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\MaxItemCompatibilityDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'MaxItemCompatibility',
        ],
        'MinItemCompatibility' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\MinItemCompatibilityDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'MinItemCompatibility',
        ],
        'ConditionEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ConditionEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ConditionEnabled',
        ],
        'ConditionValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ConditionValuesDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ConditionValues',
        ],
        'ValueCategory' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ValueCategoryDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ValueCategory',
        ],
        'ProductCreationEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ProductCreationEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ProductCreationEnabled',
        ],
        'EANEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\EANEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'EANEnabled',
        ],
        'ISBNEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ISBNEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ISBNEnabled',
        ],
        'UPCEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\UPCEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'UPCEnabled',
        ],
        'CompatibleVehicleType' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\CompatibleVehicleTypeDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'CompatibleVehicleType',
        ],
        'MaxGranularFitmentCount' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\MaxGranularFitmentCountDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'MaxGranularFitmentCount',
        ],
        'PaymentOptionsGroup' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\PaymentOptionsGroupEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PaymentOptionsGroup',
        ],
        'ShippingProfileCategoryGroup' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ProfileCategoryGroupDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ShippingProfileCategoryGroup',
        ],
        'PaymentProfileCategoryGroup' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ProfileCategoryGroupDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PaymentProfileCategoryGroup',
        ],
        'ReturnPolicyProfileCategoryGroup' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ProfileCategoryGroupDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ReturnPolicyProfileCategoryGroup',
        ],
        'VINSupported' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\VINSupportedDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'VINSupported',
        ],
        'VRMSupported' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\VRMSupportedDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'VRMSupported',
        ],
        'SellerProvidedTitleSupported' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\SellerProvidedTitleSupportedDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'SellerProvidedTitleSupported',
        ],
        'DepositSupported' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\DepositSupportedDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DepositSupported',
        ],
        'GlobalShippingEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\GlobalShippingEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'GlobalShippingEnabled',
        ],
        'AdditionalCompatibilityEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\AdditionalCompatibilityEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'AdditionalCompatibilityEnabled',
        ],
        'PickupDropOffEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\PickupDropOffEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'PickupDropOffEnabled',
        ],
        'DigitalGoodDeliveryEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\DigitalGoodDeliveryEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DigitalGoodDeliveryEnabled',
        ],
        'EpidSupported' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\EpidSupportedDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'EpidSupported',
        ],
        'KTypeSupported' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\KTypeSupportedDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'KTypeSupported',
        ],
        'ProductRequiredEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ProductRequiredEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ProductRequiredEnabled',
        ],
        'DomesticReturnsAcceptedValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\DomesticReturnsAcceptedDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DomesticReturnsAcceptedValues',
        ],
        'InternationalReturnsAcceptedValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\InternationalReturnsAcceptedDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'InternationalReturnsAcceptedValues',
        ],
        'DomesticReturnsDurationValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\DomesticReturnsDurationDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DomesticReturnsDurationValues',
        ],
        'InternationalReturnsDurationValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\InternationalReturnsDurationDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'InternationalReturnsDurationValues',
        ],
        'DomesticReturnsShipmentPayeeValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\DomesticReturnsShipmentPayeeDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DomesticReturnsShipmentPayeeValues',
        ],
        'InternationalReturnsShipmentPayeeValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\InternationalReturnsShipmentPayeeDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'InternationalReturnsShipmentPayeeValues',
        ],
        'DomesticRefundMethodValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\DomesticRefundMethodCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'DomesticRefundMethodValues',
        ],
        'InternationalRefundMethodValues' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\InternationalRefundMethodCodeType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'InternationalRefundMethodValues',
        ],
        'ReturnPolicyDescriptionEnabled' => [
          'type' => 'Apps\Dash\Packages\System\Api\Apis\Ebay\Tradingapi\Types\ReturnPolicyDescriptionEnabledDefinitionType',
          'repeatable' => false,
          'attribute' => false,
          'elementName' => 'ReturnPolicyDescriptionEnabled',
        ],
      ];

    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}